增加小爱回复
FloatTech/ZeroBot-Plugin pull request #100
Opened 2022-01-05 10:36 UTC by guohuiyuan

2022-01-06 04:34 UTC, fumiama requested changes

2022-01-06 04:34 UTC, fumiama commented on plugin_ai_reply/ai_reply.go
> +	engine.OnPrefix(`设置回复模式`).SetBlock(true).SetPriority(20).
建议使用`control.SetData()`持久化，详见

https://github.com/FloatTech/ZeroBot-Plugin/blob/2dc1fbde96ae30bea6c9c7d4c061ae6681c96e3b/plugin_nativewife/main.go#L145-L158

2022-01-06 04:34 UTC, fumiama commented on plugin_ai_reply/ai_reply.go
> +			AIReply := NewAIReply(Mode)
不要大写

2022-01-06 04:34 UTC, fumiama commented on plugin_ai_reply/ai_reply.go
> +	Mode = 1
建议不要用mode而直接留下interface，省去了判断和每次收到消息的NewAIReply

2022-01-06 07:49 UTC, guohuiyuan commented on plugin_ai_reply/ai_reply.go
> +	Mode = 1
不用mode，你怎么切换模式呢

2022-01-06 07:50 UTC, guohuiyuan commented on plugin_ai_reply/ai_reply.go
> +	engine.OnPrefix(`设置回复模式`).SetBlock(true).SetPriority(20).
你是说用control来控制模式？

2022-01-06 10:05 UTC, guohuiyuan commented on plugin_ai_reply/ai_reply.go
> +	engine.OnPrefix(`设置回复模式`).SetBlock(true).SetPriority(20).
回复模式你想怎么改

2022-01-06 12:01 UTC, fumiama commented on plugin_ai_reply/ai_reply.go
> +	engine.OnPrefix(`设置回复模式`).SetBlock(true).SetPriority(20).
目前的Mode重启之后就归零了，但是使用SetData+GetData就可以保留下来，还可以分群用不同的设置

2022-01-07 11:47 UTC, fumiama approved these changes

2022-01-07 11:47 UTC, merged