修改牛牛排行为图片发送
FloatTech/ZeroBot-Plugin pull request #1024
Opened 2024-10-13 08:27 UTC by xyy0411

2024-10-13 09:25 UTC, fumiama requested changes

2024-10-13 09:25 UTC, fumiama commented on plugin/niuniu/draw.go
> +var font, _ = os.ReadFile("./font/GlowSans.otf")
很坏，请用
```go
fontbyte, err := file.GetLazyData(text.GlowSansFontFile, control.Md5File, true)
```
并且在**使用时**再加载。看看其他插件写法。

2024-10-13 09:25 UTC, fumiama commented on plugin/niuniu/draw.go
> +		decode, _, err := image.Decode(resp.Body)
```suggestion
		decode, _, err := image.Decode(resp.Body)
		_ = resp.Body.Close()
```

2024-10-13 09:25 UTC, fumiama commented on plugin/niuniu/draw.go
> +
```go
type drawer []drawUserRanking
```

2024-10-13 09:25 UTC, fumiama commented on plugin/niuniu/draw.go
> +func drawRanking(allUsers []drawUserRanking, t bool) (img image.Image, err error) {
```suggestion
func (allUsers drawer) draw(t bool) (img image.Image, err error) {
```

2024-10-13 09:25 UTC, fumiama commented on plugin/niuniu/main.go
> +		var allUsers []drawUserRanking
```suggestion
		allUsers := make(drawer, len(m))
```

2024-10-13 09:25 UTC, fumiama commented on plugin/niuniu/main.go
> +			})
下同
```suggestion
		for i, info := range m {
			allUsers[i] = drawUserRanking{
				Name: ctx.CardOrNickName(info.UID),
				User: info,
			}
```

2024-10-13 09:25 UTC, fumiama commented on plugin/niuniu/main.go
> +		m.sort(false)
相同的流程，考虑包装为一个函数。

2024-10-13 09:25 UTC, fumiama commented on plugin/niuniu/utils.go
搞啥这是，没变化不要修改。

2024-10-13 15:09 UTC, xyy0411 commented on plugin/niuniu/main.go
> +		m.sort(false)
这个要获取名字的，封装成函数有点麻烦就算了吧

2024-10-13 15:09 UTC, xyy0411 commented on plugin/niuniu/utils.go
这玩意我都不知道怎么弄的

2024-10-13 15:27 UTC, xyy0411 commented on plugin/niuniu/main.go
> +		m.sort(false)
不考虑

2024-10-13 15:36 UTC, fumiama commented on plugin/niuniu/main.go
> +		m.sort(false)
不合并

2024-10-13 15:43 UTC, fumiama commented on plugin/niuniu/utils.go
解决

2024-10-13 15:47 UTC, xyy0411 commented on plugin/niuniu/utils.go
👍源酱厉害

2024-10-13 17:08 UTC, fumiama requested changes

2024-10-13 17:08 UTC, fumiama commented on plugin/niuniu/draw.go
> +		decode, _, err := image.Decode(resp.Body)
你以为我位置是乱写的？

2024-10-13 17:08 UTC, fumiama commented on plugin/niuniu/main.go
> +					ctx.SendChain(message.Text("ERROR:", err))
我特意加上空格你又改回去是吧

2024-10-13 17:08 UTC, fumiama commented on plugin/niuniu/draw.go
> +func (allUsers drawer) drawRanking(t bool) (img image.Image, err error) {
draw()，不懂？你以为我名字也是乱写的？

2024-10-13 17:08 UTC, fumiama commented on plugin/niuniu/draw.go
> +	Name string
不必用大写

2024-10-20 06:01 UTC, fumiama requested changes

2024-10-20 06:01 UTC, fumiama commented on plugin/niuniu/draw.go
> +	User *userInfo
你疑似有点搞笑了，让你不必大写你就一个改小写一个不动是吧😆

2024-10-20 06:01 UTC, fumiama commented on plugin/niuniu/main.go
> +		m.sort(false)
你觉得我说不合并是说着玩呢是吧

2024-10-20 14:42 UTC, fumiama approved these changes

2024-10-20 14:45 UTC, merged