update:签到失败时使用本地图片#1067
FloatTech/ZeroBot-Plugin pull request #1068
Opened 2024-11-25 09:20 UTC by vatebur

1. 修改score插件提示词，对用户更友好。
2. 图片下载失败时，会使用本地图片。

- 如果用户网络一直不通，可能会一直用某张图片作为背景
- 个人技术有限，有时间的话。帮忙多review下

2024-11-26 16:16 UTC, fumiama requested changes

2024-11-26 16:16 UTC, fumiama commented on plugin/score/sign_in.go
> +	return nil
```suggestion
	return err
```

2024-11-26 16:16 UTC, fumiama commented on plugin/score/sign_in.go
> +	for _, imgName := range files {
没必要range files给每个生成，只需随机取一个文件，判断是否符合条件，如果没有再取一个，设一个最大随机次数10次。

2024-11-27 03:04 UTC, vatebur commented
附上文件列表，`.png` 和`signin.png`是俩俩一对。
```
117840137420241126.png
117840137420241126signin.png
118346052920241126.png
118346052920241126signin.png
132628842520241113.png
132628842520241113signin.png
144191917320241114.png
144191917320241114signin.png
```

2024-11-27 04:57 UTC, fumiama approved these changes

2024-11-27 04:57 UTC, merged