优化在两个命令中使用空格分隔的体验
FloatTech/ZeroBot-Plugin pull request #112
Opened 2022-01-27 18:00 UTC by shudorcl

- fortune的设置底图功能
- b14的加密功能

***

本想继续调整藏头诗和b14的解密，但是涉及到正则触发了ORZ

2022-01-28 02:29 UTC, Yiwen-Chan commented
修改正则表达式的方式或许能更直观，such as `^加密\s?(.*)`

2022-01-28 04:11 UTC, shudorcl commented
> 修改正则表达式的方式或许能更直观，such as `^加密\s?(.*)`

了解了，稍后重新pr一份

2022-01-28 04:40 UTC, shudorcl commented
优化四个插件中使用空格分隔的体验
- 加密
- 哔哩哔哩推送
- 藏头诗
- 运势

抱歉没这么使用过pr，开开关关确实有碍观瞻

2022-01-28 11:57 UTC, fumiama requested changes

2022-01-28 11:57 UTC, fumiama commented on plugin_b14/main.go
> +	en.OnRegex(`^解密\s?(.*)`).SetBlock(true).
不要这样写，全部写在正则里

2022-01-28 11:57 UTC, fumiama commented on plugin_b14/main.go
> +	en.OnRegex(`^用(.*)解密\s?(.*)`).SetBlock(true).
同理

2022-01-28 11:57 UTC, fumiama commented on plugin_bilibili_push/bilibili_push.go
> +	en.OnRegex(`^添加订阅\s(\d+)$`, ctxext.UserOrGrpAdmin).SetBlock(true).Handle(func(ctx *zero.Ctx) {
\s?

2022-01-28 11:57 UTC, fumiama commented on plugin_bilibili_push/bilibili_push.go
> +	en.OnRegex(`^取消订阅\s(\d+)$`, ctxext.UserOrGrpAdmin).SetBlock(true).Handle(func(ctx *zero.Ctx) {
同理

2022-01-28 11:57 UTC, fumiama commented on plugin_bilibili_push/bilibili_push.go
> +	en.OnRegex(`^取消动态订阅\s(\d+)$`, ctxext.UserOrGrpAdmin).SetBlock(true).Handle(func(ctx *zero.Ctx) {
同理

2022-01-28 11:57 UTC, fumiama commented on plugin_bilibili_push/bilibili_push.go
> +	en.OnRegex(`^取消直播订阅\s(\d+)$`, ctxext.UserOrGrpAdmin).SetBlock(true).Handle(func(ctx *zero.Ctx) {
同理

2022-01-28 11:57 UTC, fumiama commented on plugin_cangtoushi/cangtoushi.go
> +		re := regexp.MustCompile("^([\u4E00-\u9FA5]{3,10})$")
不要这样，全部写在一个正则

2022-01-28 11:57 UTC, fumiama commented on plugin_cangtoushi/cangtoushi.go
> +	engine.OnRegex(`藏尾诗\s?(.*)`).SetBlock(true).Handle(func(ctx *zero.Ctx) {
同理

2022-01-28 11:57 UTC, fumiama commented on plugin_fortune/fortune.go
> +	en.OnRegex(`^设置底图\s(.*)`).SetBlock(true).
\s?

2022-01-28 11:57 UTC, fumiama commented on plugin_fortune/fortune.go
> +			i, ok := index[strings.Trim(ctx.State["regex_matched"].([]string)[1], " ")]
不需要trim

2022-01-28 12:07 UTC, shudorcl commented on plugin_bilibili_push/bilibili_push.go
> +	en.OnRegex(`^添加订阅\s(\d+)$`, ctxext.UserOrGrpAdmin).SetBlock(true).Handle(func(ctx *zero.Ctx) {
\s 是因为发现部分用户习惯于`指令 参数`这种触发方式，会导致指令无法有效触发（如`设置底图 原神`）或者参数中加入空格（如`加密 foo`），一开始不希望改动正则触发逻辑使用Trim，接受建议后则使用\s

2022-01-28 12:07 UTC, shudorcl commented on plugin_fortune/fortune.go
> +			i, ok := index[strings.Trim(ctx.State["regex_matched"].([]string)[1], " ")]
这里是我的疏忽，抱歉

2022-01-28 12:22 UTC, shudorcl commented on plugin_bilibili_push/bilibili_push.go
> +	en.OnRegex(`^添加订阅\s(\d+)$`, ctxext.UserOrGrpAdmin).SetBlock(true).Handle(func(ctx *zero.Ctx) {
抱歉，是我的疏忽，以上解释无效

2022-01-28 12:22 UTC, shudorcl commented on plugin_b14/main.go
> +	en.OnRegex(`^解密\s?(.*)`).SetBlock(true).
在之前的尝试中发现使用反引号括起的字符串会使`\u`识别为无效转义序列，而使用双引号括起的字符串则无法将`\s`识别为转义字符，且经过简单查找后没有相关信息，故出此下策。
现在看来使用`^解密\s?([一-踀]*[㴁-㴆]?)$`可能可以实现

2022-01-28 12:24 UTC, fumiama commented on plugin_b14/main.go
> +	en.OnRegex(`^解密\s?(.*)`).SetBlock(true).
确实，可以这样做

2022-01-29 05:47 UTC, fumiama approved these changes

2022-01-29 05:48 UTC, merged