feat:添加月幕galgame网站图
FloatTech/ZeroBot-Plugin pull request #138
Opened 2022-02-26 15:05 UTC by guohuiyuan

2022-02-26 15:24 UTC, fumiama commented on plugin/ai_reply/ai_tts.go
> +func (t *ttsInstances) setDefaultSoundMode(name string) {
加把锁

2022-02-26 15:24 UTC, fumiama commented on plugin/ymgal/model.go
> +type Ymgal struct {
不用public

2022-02-26 15:26 UTC, fumiama commented on plugin/ymgal/model.go
> +	ymgalJSON, err := json.Marshal(ymgalMap)
不好，建议手动复制

2022-02-26 15:32 UTC, fumiama commented on plugin/ymgal/ymgal.go
> +			fmt.Println(y)
不要用fmt直接打印，实在要打印应当用logrus

2022-02-26 15:32 UTC, fumiama commented on plugin/ymgal/ymgal.go
> +	engine = control.Register("ymgal", order.AcquirePrio(), &control.Options{
放init()

2022-02-26 15:32 UTC, fumiama commented on plugin/ymgal/model.go
> +	for i := 1; i <= maxCgPageNumber; i++ {
不好，建议不要每次遍历全部，你去看看煎蛋我怎么改的。

2022-02-26 15:32 UTC, fumiama commented on plugin/ymgal/model.go
> +	maxCgPageNumber       int
不要有这种全局变量

2022-02-26 15:33 UTC, fumiama commented on plugin/ymgal/ymgal.go
> +	var m message.Message
```go
m := message.Message{message.CustomNode(
	ctx.Event.Sender.NickName,
	ctx.Event.UserID,
	y.Title,
)}
```

2022-02-26 15:35 UTC, fumiama commented on plugin/ymgal/model.go
> +	ymgalJSON, err := json.Marshal(ymgalMap)
其他类似地方同理

2022-02-26 15:35 UTC, fumiama commented on plugin/ymgal/model.go
> +	for i := 1; i <= maxCgPageNumber; i++ {
其他类似地方同理

2022-02-26 15:47 UTC, guohuiyuan commented on plugin/ymgal/model.go
> +	ymgalJSON, err := json.Marshal(ymgalMap)
手动复制是什么意思，传什么参数

2022-02-27 03:44 UTC, fumiama approved these changes

2022-02-27 03:44 UTC, fumiama commented on plugin/ai_reply/ai_tts.go
> +	mu sync.RWMutex
最好是
```go
type ttsInstances struct {
    sync.RWMutex
    ...
}

t.Lock()
t.Unlock()
```

2022-02-27 03:52 UTC, fumiama approved these changes

2022-02-27 03:52 UTC, fumiama commented on plugin/ai_reply/ai_tts.go
> +	mu sync.RWMutex
不用写mu，看我的示例

2022-02-27 03:53 UTC, fumiama requested changes

2022-02-27 03:53 UTC, fumiama commented on plugin/ai_reply/ai_tts.go
> +	for i, s := range t.l {
另外，这里加Rlock

2022-02-27 03:55 UTC, fumiama requested changes

2022-02-27 03:55 UTC, fumiama commented on plugin/ai_reply/ai_tts.go
>  func (t *ttsInstances) List() []string {
当然，List()的遍历也要加Rlock

2022-02-27 10:51 UTC, fumiama approved these changes

2022-02-27 10:57 UTC, merged