摸鱼日历
FloatTech/ZeroBot-Plugin pull request #143
Opened 2022-03-07 15:15 UTC by LingMuXing

2022-03-07 15:27 UTC, fumiama requested changes
过lint

2022-03-08 06:21 UTC, Yiwen-Chan commented on plugin/moyu_calendar/calendar.go
> +			"- 日历]",
这里多了个中括号

2022-03-08 06:22 UTC, Yiwen-Chan commented on plugin/moyu_calendar/calendar.go
> +		a := rili()
这里应该使用更明确的变量名

2022-03-08 06:23 UTC, Yiwen-Chan commented on plugin/moyu_calendar/calendar.go
> +	res, _ := http.Get(url)
这里应该加上错误处理并返回

2022-05-07 14:35 UTC, fumiama approved these changes

2022-05-07 14:35 UTC, merged