增加城市疫情查询
FloatTech/ZeroBot-Plugin pull request #146
Opened 2022-03-10 06:17 UTC by sky-rainy

2022-03-10 07:57 UTC, fumiama requested changes

2022-03-10 07:57 UTC, fumiama commented on plugin/epidemic/epidemic.go
> +	servicename = "qe"
服务名过于费解，建议更换。

2022-03-10 07:57 UTC, fumiama commented on plugin/epidemic/epidemic.go
> +	engine.OnRegex(`^(.*)疫情$`).SetBlock(true).
用OnSuffix

2022-03-10 07:57 UTC, fumiama commented on plugin/epidemic/epidemic.go
> +	info := gjson.ParseBytes(response)
建议用json.Unmarshal()

2022-03-10 07:57 UTC, fumiama commented on plugin/epidemic/epidemic.go
> +	for _, v := range dqnmae {
建议用map

2022-03-10 07:57 UTC, fumiama commented on plugin/epidemic/epidemic.go
> +	return message.Text(returnText + "\n" + fmt.Sprintf(" 更新时间：%s", data.Get("lastUpdateTime").String()) + "\n" + "温馨提示：请大家做好防疫工作，出门带好口罩！")
建议直接返回string，包装由调用者进行。

2022-03-10 07:57 UTC, fumiama commented on plugin/epidemic/epidemic.go
> +	params := make(map[string]interface{})
没用

2022-03-10 07:57 UTC, fumiama commented on plugin/epidemic/epidemic.go
> +	response := sendRequest(txurl, params, "GET")
建议用web.GetData()

2022-03-10 07:57 UTC, fumiama commented on plugin/epidemic/request.go
> +// Package epidemic 城市疫情查询
功能冗余，建议删除本文件。

2022-03-10 09:30 UTC, fumiama requested changes

2022-03-10 09:30 UTC, fumiama commented on plugin/epidemic/epidemic.go
> +	servicename = "queryEpidemic"
全小写，最好直接用包名epidemic

2022-03-10 09:30 UTC, fumiama commented on plugin/epidemic/epidemic.go
> +			data, returnbool := queryEpidemic(region)
你测试了吗，onsuffix还用regex_matched肯定跑不通。

2022-03-10 09:30 UTC, fumiama commented on plugin/epidemic/epidemic.go
> +	dataInfo := make(map[string]string)
你没有明白我的意思，我是说用json代替gjson，这样就可以把键解析到map，不用再for _, v := range dqnmae查找。你实在不明白就不改了，我之后再改。

2022-03-10 09:47 UTC, Yiwen-Chan commented on plugin/epidemic/epidemic.go
> +	dataInfo := make(map[string]string)
应该解析到struct

2022-03-10 13:54 UTC, wdvxdr1123 commented on plugin/epidemic/epidemic.go
> +			text := ""
text := ctx.State["args"].(string)

2022-03-10 13:54 UTC, wdvxdr1123 commented on plugin/epidemic/epidemic.go
> +	citydata := Rcity(&e.AreaTree[0], findCityName)
check size not zero

2022-03-10 13:54 UTC, wdvxdr1123 commented on plugin/epidemic/epidemic.go
> +	Children []Area `json:"children"`
用`[]*Area`更好

2022-03-10 13:58 UTC, wdvxdr1123 commented on plugin/epidemic/epidemic.go
> +		log.Errorln("[txurl-err]:", err)
need return

2022-03-10 13:58 UTC, wdvxdr1123 commented on plugin/epidemic/epidemic.go
> +	} else {
remove else, just return &City{xxxx}

2022-03-10 14:01 UTC, wdvxdr1123 commented on plugin/epidemic/epidemic.go
> +func queryEpidemic(findCityName string) *CityInfo {
可以直接返回(city *Area, time string), 就不用定义 CityInfo  了

2022-03-10 15:11 UTC, fumiama commented on plugin/epidemic/epidemic.go
> +type Result struct {
warning也要消除

2022-03-11 01:02 UTC, Yiwen-Chan commented on plugin/epidemic/epidemic.go
> +	_ = json.Unmarshal(response, &r)
这里需要处理错误，下同

2022-03-11 08:10 UTC, fumiama approved these changes

2022-03-11 08:10 UTC, merged