Commits on Mar 20, 2022 游戏王搜卡插件
FloatTech/ZeroBot-Plugin pull request #159
Opened 2022-03-20 06:31 UTC by fangliuyu

本插件使用正则扒取网页"[https://www.ygo-sem.cn/"获取的卡片信息。](https://www.ygo-sem.cn/%22%E8%8E%B7%E5%8F%96%E7%9A%84%E5%8D%A1%E7%89%87%E4%BF%A1%E6%81%AF%E3%80%82)

1.指令：ygo XXX
①xxx为卡名：查询卡名为XXX的卡信息
②xxx为“随机一卡”：随机展示一张卡
2.指令：x
①x为搜索列表对应的数字：获取对应的卡片信息
②x为“下一页”：搜索列表翻到下一页

2022-03-26 15:07 UTC, wdvxdr1123 reviewed
简单看了下

2022-03-26 15:07 UTC, wdvxdr1123 commented on plugin/ygo/plugin_ygo.go
> +				case e := <-next.Next():
对于需要的场景，请使用 
ch,cancel := next.Repeat()
defer cancel()

2022-03-26 15:07 UTC, wdvxdr1123 commented on plugin/ygo/plugin_ygo.go
> +									fmt.Println("网页数据读取错误：", err)
需要return

2022-03-26 15:07 UTC, wdvxdr1123 commented on plugin/ygo/plugin_ygo.go
> +			var next = zero.NewFutureEvent("message", 999, false, zero.RegexRule(`(下一页)|\d+`), zero.OnlyGroup, zero.CheckUser(ctx.Event.UserID))
考虑增加手动取消的指令

2022-03-26 23:51 UTC, fangliuyu commented on plugin/ygo/plugin_ygo.go
> +			var next = zero.NewFutureEvent("message", 999, false, zero.RegexRule(`(下一页)|\d+`), zero.OnlyGroup, zero.CheckUser(ctx.Event.UserID))
已增加取消指令

2022-03-26 23:51 UTC, fangliuyu commented on plugin/ygo/plugin_ygo.go
> +									fmt.Println("网页数据读取错误：", err)
已更改完成

2022-03-26 23:55 UTC, fangliuyu commented on plugin/ygo/plugin_ygo.go
> +				case e := <-next.Next():
已改为使用Repeat()
但是如果在Repeat()下面直接加defer cancel()，运行的时候报错了。
我将cancel()加入到了每个指令分支下面。

![QQ截图20220327075500](https://user-images.githubusercontent.com/101934327/160260915-5e6e802d-c355-48f7-a487-db20d302b817.png)

2022-03-27 06:30 UTC, fumiama requested changes
建议先同步一下最新仓库进度，以使ci通过。另外之前在zbpdata的建议，请作改动。

2022-03-27 06:31 UTC, wdvxdr1123 commented on plugin/ygo/plugin_ygo.go
> +						cancel()
这里cancel不对

2022-03-28 05:38 UTC, fumiama requested changes

2022-03-28 05:38 UTC, fumiama commented on plugin/ygo/plugin_ygo.go
> +func reqwith(url string, method string, referer string, ua string) (data []byte, err error) {
请直接调用web.GetDataWith

2022-03-28 05:38 UTC, fumiama commented on plugin/ygo/plugin_ygo.go
> +			maxnumber, _ := strconv.Atoi(listmax)
这个err不能忽略

2022-03-28 05:38 UTC, fumiama commented on plugin/ygo/plugin_ygo.go
> +					nextcmd := e.Message.String() //获取下一个指令
e.Event.Message.String()

2022-03-28 05:38 UTC, fumiama commented on plugin/ygo/plugin_ygo.go
> +	en.OnRegex(`^(.{0,2})每日分享卡片$`, zero.OnlyGroup, zero.AdminPermission).SetBlock(true).Handle(func(ctx *zero.Ctx) {
已经不需要了，可以移除

2022-03-28 05:38 UTC, fumiama commented on plugin/ygo/plugin_ygo.go
> +	process.CronTab.AddFunc("00 12 * * *", func() {
同理，可以移除。定时完全由job负责。

2022-04-04 23:50 UTC, closed without merging