👍 添加查成分功能，修改bilibili插件的正则
FloatTech/ZeroBot-Plugin pull request #171
Opened 2022-03-27 14:06 UTC by guohuiyuan

2022-03-28 05:29 UTC, fumiama requested changes

2022-03-28 05:29 UTC, fumiama commented on plugin/bilibili/api.go
> +func search(keyword string) (*gjson.Result, error) {
应当直接返回uid而非gjson

2022-03-28 05:29 UTC, fumiama commented on plugin/bilibili/api.go
> +func followings(uid string) (*gjson.Result, error) {
同理，应当直接返回uname

2022-03-28 05:29 UTC, fumiama commented on plugin/bilibili/api.go
> +	result.Name = gjson.Get(cardStr, "card.name").String()
建议直接用json.Unmarshal()

2022-03-28 05:29 UTC, fumiama commented on plugin/bilibili/api.go
> +	gjson.Get(medalStr, "data.list").ForEach(func(key, value gjson.Result) bool {
同上，建议直接用json.Unmarshal()

2022-03-28 05:29 UTC, fumiama commented on plugin/bilibili/api.go
> +		return result, errors.New("查牌子需要设置b站cookie，请发送命令设置cookie，例如\"设置b站cookie SESSDATA=82da790d,1663822823,06ecf*31\"")
建议将此err定义为全局变量ErrNeedCookie

2022-03-28 05:29 UTC, fumiama commented on plugin/bilibili/model.go
> +	cachePath = engine.DataFolder() + "cache/"
不要做为全局变量，在engine被赋值前调用会出错。

2022-03-28 05:29 UTC, fumiama commented on plugin/bilibili/info.go
> +func int2rbg(t int64) (int64, int64, int64) {
应当用
```go
var buf [8]byte
binary.LittleEndian.PutInt64(buf[:], t)
b, g, r := int64(buf[0]), int64(buf[1]), int64(buf[2])
```

2022-03-28 05:29 UTC, fumiama commented on plugin/bilibili/model.go
> +	dbfile    = engine.DataFolder() + "bilibili.db"
不要做为全局变量，在engine被赋值前调用会出错。

2022-03-28 05:29 UTC, fumiama commented on plugin/bilibili_push/bilibili_push.go
> +	data, err := web.PostData(liveListURL, "application/json", bytes.NewBuffer(b))
bytes.NewReader()

2022-03-28 06:09 UTC, guohuiyuan commented on plugin/bilibili/api.go
> +func search(keyword string) (*gjson.Result, error) {
之前的>user info [xxx]用了这个接口，这是复用接口

2022-03-28 06:32 UTC, guohuiyuan commented on plugin/bilibili/api.go
> +func search(keyword string) (*gjson.Result, error) {
一起改掉也行

2022-03-28 15:25 UTC, guohuiyuan commented on plugin/bilibili/info.go
> +func int2rbg(t int64) (int64, int64, int64) {
这个颜色顺序是正确的吗，我不知道啊

2022-03-29 04:48 UTC, fumiama approved these changes

2022-03-29 05:03 UTC, merged