新增 {gid} {groupname}
FloatTech/ZeroBot-Plugin pull request #186
Opened 2022-04-09 06:00 UTC by myrnfc

Add {gid} {groupname} ; replace {id} with {uid} ; Write UnescapeCQCodeText  into database instead

2022-04-09 10:26 UTC, fumiama requested changes

2022-04-09 10:26 UTC, fumiama commented on plugin/manager/manager.go
> +func UnescapeCQCodeText(raw string) string {
message.UnescapeCQCodeText()

2022-04-09 15:44 UTC, myrnfc commented on plugin/manager/manager.go
> +func UnescapeCQCodeText(raw string) string {
message.UnescapeCQCodeText()替换的顺序好像有问题 在onebot-mirai上会导致一些问题

2022-04-09 15:47 UTC, fumiama requested changes

2022-04-09 15:47 UTC, fumiama commented on plugin/manager/manager.go
> +func UnescapeCQCodeText(raw string) string {
你可以pr zb

2022-04-10 03:46 UTC, fumiama approved these changes

2022-04-10 03:46 UTC, merged