👍 添加聊天热词
FloatTech/ZeroBot-Plugin pull request #192
Opened 2022-04-16 11:55 UTC by guohuiyuan

2022-04-16 16:08 UTC, fumiama requested changes

2022-04-16 16:08 UTC, fumiama commented on plugin/word_count/word_count.go
> +				ctx.SendChain(message.Text(fmt.Sprintf("%s未加入%s(%d),无法获得热词呢", zero.BotConfig.NickName[0], group.Name, gid)))
不需要Sprintf，直接将各个元素用逗号隔开即可
```go
message.Text(zero.BotConfig.NickName[0], "未加入", group.Name, "(", gid, "),无法获得热词呢")
```

2022-04-16 16:08 UTC, fumiama commented on plugin/word_count/word_count.go
> +	cachePath := engine.DataFolder() + "cache/"
启动时清一下cache

2022-04-16 16:08 UTC, fumiama commented on plugin/word_count/word_count.go
> +					tex := strings.TrimSpace(message.ParseMessage(binary.StringToBytes(v.Raw)).ExtractPlainText())
message.ParseMessageFromString()

2022-04-16 16:08 UTC, fumiama commented on plugin/word_count/word_count.go
> +type Pair struct {
小写

2022-04-16 16:08 UTC, fumiama commented on plugin/word_count/word_count.go
> +type PairList []Pair
小写

2022-04-16 16:13 UTC, fumiama commented on plugin/word_count/word_count.go
> +		for _, v := range strings.Split(binary.BytesToString(data), "\r\n") {
应当用scanner

2022-04-16 16:15 UTC, fumiama commented on plugin/word_count/word_count.go
> +	stopwordsMap := make(map[string]int)
map作为查找意义不大，可以参考wordle的实现，用list。

2022-04-17 03:12 UTC, guohuiyuan commented on plugin/word_count/word_count.go
> +				ctx.SendChain(message.Text(fmt.Sprintf("%s未加入%s(%d),无法获得热词呢", zero.BotConfig.NickName[0], group.Name, gid)))
gid是int64类型，不想转类型了

2022-04-17 03:13 UTC, guohuiyuan commented on plugin/word_count/word_count.go
> +	cachePath := engine.DataFolder() + "cache/"
下面写了

2022-04-17 03:28 UTC, fumiama commented on plugin/word_count/word_count.go
> +				ctx.SendChain(message.Text(fmt.Sprintf("%s未加入%s(%d),无法获得热词呢", zero.BotConfig.NickName[0], group.Name, gid)))
不用转换，你看我代码，直接填。message.Text接受任意interface{}

2022-04-17 03:30 UTC, guohuiyuan commented on plugin/word_count/word_count.go
> +		for _, v := range strings.Split(binary.BytesToString(data), "\r\n") {
改成数组的话，就就不用遍历，直接分割😂

2022-04-17 04:55 UTC, fumiama requested changes

2022-04-17 04:55 UTC, fumiama commented on plugin/word_count/word_count.go
> +		_, _ = file.GetLazyData(engine.DataFolder()+"stopwords.txt", false, false)
检查err

2022-04-17 04:55 UTC, fumiama commented on plugin/word_count/word_count.go
> +		if err != nil {
这个err没有必要

2022-04-17 04:55 UTC, fumiama commented on plugin/word_count/word_count.go
> +	go func() {
这没删干净啊

2022-04-17 04:55 UTC, fumiama commented on plugin/word_count/word_count.go
> +	engine.OnRegex(`^热词\s?(\d*)\s?(\d*)$`, zero.OnlyGroup, getStopwords).Limit(ctxext.LimitByUser).SetBlock(true).
上面那个函数getStopwords可以直接嵌进来，参见omikuji

2022-04-17 13:23 UTC, fumiama approved these changes

2022-04-17 13:24 UTC, merged