👍 添加漫画猫插件
FloatTech/ZeroBot-Plugin pull request #204
Opened 2022-04-25 05:40 UTC by guohuiyuan

2022-04-26 05:53 UTC, fumiama requested changes
问题较多，建议理顺思路，选择最优解而不是粗暴的解法。

2022-04-26 05:53 UTC, fumiama commented on plugin/maofly/maofly.go
> +	LZString "github.com/Lazarus/lz-string-go"
小写

2022-04-26 05:53 UTC, fumiama commented on plugin/maofly/maofly.go
> +			files = make([]string, 0)
```go
files = files[:0]
```

2022-04-26 05:53 UTC, fumiama commented on plugin/maofly/maofly.go
> +	files         []string
```go
files = make([]string, 0, 32)
```

2022-04-26 05:53 UTC, fumiama commented on plugin/maofly/maofly.go
> +			if len(c) == 0 || err != nil {
已经判断过err，无需或运算

2022-04-26 05:53 UTC, fumiama commented on plugin/maofly/maofly.go
> +				err := unzip(zipName, ".")
请使用增量更新，不要每次解压全部，下载全部，打包全部。提供更多指令，如上传哪一/几章，减少下载量。本地zip启动时清空。

2022-04-26 05:53 UTC, fumiama commented on plugin/maofly/maofly.go
> +			if file.IsExist(zipName) {
文件操作要加锁

2022-04-26 05:53 UTC, fumiama commented on plugin/maofly/maofly.go
> +			chanTask = make(chan string, len(c))
不要每次make，而应该上移到声明处。

2022-04-26 05:53 UTC, fumiama commented on plugin/maofly/maofly.go
> +			chanImageUrls = make(chan string, 1000000)
同。另外这也太大了，32足够了。

2022-04-26 05:53 UTC, fumiama commented on plugin/maofly/maofly.go
> +				waitGroup.Add(1)
放到循环外
```go
waitGroup.Add(len(c))
```

2022-04-26 05:53 UTC, fumiama commented on plugin/maofly/maofly.go
> +				waitGroup.Add(1)
同

2022-04-26 05:53 UTC, fumiama commented on plugin/maofly/maofly.go
> +				key := fmt.Sprintf("%s|%d|%d|%s|%s", title, i, c[i].dataSort, c[i].href, c[i].title)
请使用变长参数
```go
go getImgs(title, i, c[i].dataSort, c[i].href, c[i].title)
```

2022-04-26 05:53 UTC, fumiama commented on plugin/maofly/maofly.go
> +			go checkOK(len(c))
不需要，有channel足够了

2022-04-26 05:53 UTC, fumiama commented on plugin/maofly/maofly.go
> +			fmt.Println("Zipped File:", zipName)
不要向标准输出直接打印任何内容，而应该使用logrus.Debugln

2022-04-26 05:53 UTC, fumiama commented on plugin/maofly/maofly.go
> +		log.Errorln("[maofly]", err)
请显式返回err并处理，不要吐到log，没有用。
```go
func search(key string) (text string, al []a, err error)
```

2022-04-26 05:53 UTC, fumiama commented on plugin/maofly/maofly.go
> +		return
这里就很好

2022-04-26 05:53 UTC, fumiama commented on plugin/maofly/maofly.go
> +func checkOK(total int) {
实现很不优雅，考虑移除

2022-04-26 05:53 UTC, fumiama commented on plugin/maofly/maofly.go
> +func getImgs(key string) {
在这里需要一个err的chan做多次重试仍失败后的错误处理

2022-04-26 05:53 UTC, fumiama commented on plugin/maofly/maofly.go
> +			files = append(files, filePath)
自己维护一个局部变量files，整个结束后一并append到全局，全局的记得加锁。

2022-04-26 05:53 UTC, fumiama commented on plugin/maofly/maofly.go
> +		data, err := web.RequestDataWith(web.NewDefaultClient(), fileURL, "GET", "", ua)
用file.DownloadTo

2022-04-26 06:26 UTC, guohuiyuan commented on plugin/maofly/maofly.go
> +				err := unzip(zipName, ".")
这个你看后面，已下载的图片直接打包，解压以前的打包文件是因为，有些图片网址下载经常400，需要反复下载

2022-04-26 06:33 UTC, guohuiyuan commented on plugin/maofly/maofly.go
> +func getImgs(key string) {
这个地方必须要有数据，要不然会少章节

2022-04-26 06:34 UTC, guohuiyuan commented on plugin/maofly/maofly.go
> +func getImgs(key string) {
err的chan不知道怎么写

2022-04-26 08:01 UTC, fumiama commented on plugin/maofly/maofly.go
> +				err := unzip(zipName, ".")
这个需要在下载时就解决，而不是留到之后。只要有一张图片错误就不能上传，更不能打包。

2022-04-26 08:02 UTC, fumiama commented on plugin/maofly/maofly.go
> +func getImgs(key string) {
> 这个地方必须要有数据，要不然会少章节

必须有数据就用waitgroup等待，或者考虑暂时放弃一部分多线程。

2022-04-26 09:03 UTC, guohuiyuan commented on plugin/maofly/maofly.go
> +func getImgs(key string) {
> > 这个地方必须要有数据，要不然会少章节
> 
> 必须有数据就用waitgroup等待，或者考虑暂时放弃一部分多线程。
那个checkok就是检查，是否爬完所有章节的，这部分我是仿造https://www.topgoer.com/%E5%B9%B6%E5%8F%91%E7%BC%96%E7%A8%8B/%E7%88%AC%E8%99%AB%E5%B0%8F%E6%A1%88%E4%BE%8B.html 这里写的

2022-04-26 09:09 UTC, fumiama commented on plugin/maofly/maofly.go
> +func getImgs(key string) {
这种check不是很好，多用了一个chan，且容易死锁造成goroutine泄露。换成waitgruop自然一点。

或者先用单线程写，优先让代码简洁起来，一次少下一些，比如限制一次下一个章节。后续再丰富。

2022-04-26 09:10 UTC, guohuiyuan commented on plugin/maofly/maofly.go
> +func getImgs(key string) {
> > 这个地方必须要有数据，要不然会少章节
> 
> 必须有数据就用waitgroup等待，或者考虑暂时放弃一部分多线程。

重试几次就会有数据了，它报的错误是503，10次应该不会失败

2022-04-26 09:11 UTC, fumiama commented on plugin/maofly/maofly.go
> +func getImgs(key string) {
不能做这个假设，应当考虑如果没下好的处理。

2022-04-26 09:12 UTC, guohuiyuan commented
这个确实，之前没考虑到压缩文件太大，上传速度太慢，之前考虑的一般人的需求肯定是喜欢一次性全下载




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月26日(星期二) 下午5:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FloatTech/ZeroBot-Plugin] 👍 添加漫画猫插件 (PR #204)





 
@fumiama commented on this pull request.
 
 
In plugin/maofly/maofly.go:
 &gt; +} + +func checkOK(total int) { +	count := 0 +	for { +		_ = <-chanTask +		count++ +		if count == total { +			close(chanImageUrls) +			break +		} +	} +	waitGroup.Done() +} + +func getImgs(key string) {  
这种check不是很好，多用了一个chan，且容易死锁造成goroutine泄露。换成waitgruop自然一点。
 
或者先用单线程写，优先让代码简洁起来，一次少下一些，比如限制一次下一个章节。后续再丰富。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2022-04-26 09:13 UTC, fumiama commented
> 这个确实，之前没考虑到压缩文件太大，上传速度太慢，之前考虑的一般人的需求肯定是喜欢一次性全下载

是这样，要不然群文件也遭不住😂

2022-04-26 09:16 UTC, guohuiyuan commented
> > 这个确实，之前没考虑到压缩文件太大，上传速度太慢，之前考虑的一般人的需求肯定是喜欢一次性全下载
> 
> 是这样，要不然群文件也遭不住😂

我等下搞个阉割版吧，选择漫画标题，选择章节，然后发送合并转发的图片

2022-04-27 01:52 UTC, fumiama commented
> 我等下搞个阉割版吧，选择漫画标题，选择章节，然后发送合并转发的图片，令我担忧的是，这个网站图片经常400

会不会是你的多线程请求太频繁被限速了，你可以单线程试试。多线程被限速的话，还要错误处理，重新下载等等，平均一页可能要重下3、4次，可能反而不如单线程快。

2022-04-27 16:46 UTC, closed without merging

2022-04-27 17:10 UTC, guohuiyuan commented
直接发图片被屏蔽，如果压缩图片上传的看的非常不方便，所以感觉鸡肋了，等找到正确发图姿势，再整插件

2022-04-28 05:01 UTC, fumiama commented
也好，我觉得这个功能其实还是比较有用的。