🎨 优化vtb插件代码，更换shadiao的api
FloatTech/ZeroBot-Plugin pull request #206
Opened 2022-04-27 17:06 UTC by guohuiyuan

2022-04-28 05:04 UTC, fumiama requested changes

2022-04-28 05:04 UTC, fumiama commented on plugin/vtb_quotation/vtb_quotation.go
> +						reg := regexp.MustCompile(regStr)
提到全局变量

2022-04-28 09:37 UTC, fumiama approved these changes

2022-04-28 09:37 UTC, merged

2022-04-29 06:22 UTC, omanikk commented
大佬大佬 以前vtb不是用的这个网址吗 vtbkeyboard.moe  现在换网址了？

2022-04-29 06:23 UTC, guohuiyuan commented
换的是shadiao插件的api





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月29日(星期五) 下午2:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FloatTech/ZeroBot-Plugin] 🎨 优化vtb插件代码，更换shadiao的api (PR #206)





 
大佬大佬 以前vtb不是用的这个网址吗 vtbkeyboard.moe  现在换网址了？
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
您收到此消息是因为您编写了该主题。消息 ID：<FloatTech/ZeroBot-Plugin/pull/206/c1112913872 @ github 。com&gt;

2022-04-29 06:28 UTC, omanikk commented
好滴  明白了  大佬辛苦了