修复单身狗技能逻辑
FloatTech/ZeroBot-Plugin pull request #224
Opened 2022-05-11 15:01 UTC by fangliuyu

2022-05-11 16:35 UTC, fumiama requested changes

2022-05-11 16:35 UTC, fumiama commented on plugin/qqwife/qqmapwife.go
> +			"今天你向ta表白了，ta给了你一个拥抱后插肩而过\n",
擦肩而过

2022-05-11 16:35 UTC, fumiama commented on plugin/qqwife/qqmapwife.go
> +	sendtext    = [][]string{
sendtext = [...][]string

2022-05-11 16:35 UTC, fumiama commented on plugin/qqwife/qqmapwife.go
> +			husband, ok := qqwifegroup[gid][-uid]
需要先判断qqwifegroup[gid]是否ok才能进行下一步判断，否则会闪退。你可以把
https://github.com/FloatTech/ZeroBot-Plugin/blob/2ae1892ab02499f688b63329fd230a6db66eaec6/plugin/qqwife/qqmapwife.go#L122-L124
移到这之前，保证非空。

2022-05-11 16:35 UTC, fumiama commented on plugin/qqwife/qqmapwife.go
> +	engine.OnRegex(`^娶(\d+|\[CQ:at,qq=(\d+)\])`, checkdog, zero.OnlyGroup).SetBlock(true).Limit(singledogCD.LimitByUser).
把checkdog放在zero.OnlyGroup之后以避免私聊触发闪退

2022-05-11 22:25 UTC, fangliuyu commented on plugin/qqwife/qqmapwife.go
> +			"今天你向ta表白了，ta给了你一个拥抱后插肩而过\n",
以更改

2022-05-11 22:25 UTC, fangliuyu commented on plugin/qqwife/qqmapwife.go
> +	sendtext    = [][]string{
OK

2022-05-11 22:25 UTC, fangliuyu commented on plugin/qqwife/qqmapwife.go
> +			husband, ok := qqwifegroup[gid][-uid]
已到了判断已娶人的前面

2022-05-11 22:25 UTC, fangliuyu commented on plugin/qqwife/qqmapwife.go
> +	engine.OnRegex(`^娶(\d+|\[CQ:at,qq=(\d+)\])`, checkdog, zero.OnlyGroup).SetBlock(true).Limit(singledogCD.LimitByUser).
已挪到后面

2022-05-12 03:21 UTC, fumiama approved these changes

2022-05-12 03:22 UTC, merged