修复CD共用问题，新增功能
FloatTech/ZeroBot-Plugin pull request #229
Opened 2022-05-15 01:34 UTC by fangliuyu

2022-05-15 05:18 UTC, fumiama requested changes
请在当前插件基础上修改

2022-05-15 07:01 UTC, fumiama requested changes
不是说所有地方都要用汉字。你看原来的代码，只在关键地方用了汉字起到提示性的作用。全部用汉字反而会增大理解难度。

2022-05-15 12:18 UTC, fumiama requested changes

2022-05-15 12:18 UTC, fumiama commented on plugin/qqwife/qqmapwife.go
> +func (db *婚姻登记) 登记情况(gid int64) (ok bool) {
有登记

2022-05-15 12:18 UTC, fumiama commented on plugin/qqwife/qqmapwife.go
> +func (db *婚姻登记) 登记(ctx *zero.Ctx, gid, uid, target int64) {
不要传入ctx而应当直接传入名字

2022-05-15 12:18 UTC, fumiama commented on plugin/qqwife/qqmapwife.go
> +func (db *婚姻登记) 新档案(gid int64) {
不需要这个。参见之前的“登记”函数，只要在登记前确保map存在即可。

2022-05-15 12:18 UTC, fumiama commented on plugin/qqwife/qqmapwife.go
> +			if !民政局.登记情况(gid) {
不需要

2022-05-15 12:18 UTC, fumiama commented on plugin/qqwife/qqmapwife.go
> +				if !民政局.登记情况(gid) {
不需要

2022-05-15 12:18 UTC, fumiama commented on plugin/qqwife/qqmapwife.go
> +func (db *婚姻登记) 办理离婚(gid, wife int64) {
离婚是双向的，应当拆分为"休妻/休夫"，取消传入的负数，把正负转换逻辑控制在函数之内，不要暴露出来。

2022-05-16 00:39 UTC, fangliuyu commented on plugin/qqwife/qqmapwife.go
> +func (db *婚姻登记) 办理离婚(gid, wife int64) {
休妻/休夫已通过参数传入函数内

2022-05-16 00:39 UTC, fangliuyu commented on plugin/qqwife/qqmapwife.go
> +				if !民政局.登记情况(gid) {
已删除

2022-05-16 00:39 UTC, fangliuyu commented on plugin/qqwife/qqmapwife.go
> +			if !民政局.登记情况(gid) {
已删除

2022-05-16 00:40 UTC, fangliuyu commented on plugin/qqwife/qqmapwife.go
> +func (db *婚姻登记) 新档案(gid int64) {
已删除

2022-05-16 00:40 UTC, fangliuyu commented on plugin/qqwife/qqmapwife.go
> +func (db *婚姻登记) 登记(ctx *zero.Ctx, gid, uid, target int64) {
已修改函数参数

2022-05-16 02:37 UTC, fumiama approved these changes

2022-05-16 02:40 UTC, fumiama requested changes
请注意注释格式，除了特殊注释`//nolint`，`//`后都要有空格。

2022-05-16 02:40 UTC, fumiama commented on plugin/qqwife/qqmapwife.go
> +func (db *婚姻登记) 登记情况(gid int64) (ok bool) {
这个改一下名字

2022-05-16 02:40 UTC, fumiama commented on plugin/qqwife/qqmapwife.go
> +func (db *婚姻登记) 办理离婚(gid, wife int64, gender int) {
分成两个函数

2022-05-16 02:40 UTC, fumiama commented on plugin/qqwife/qqmapwife.go
> +	//单生狗专属技能
单身

2022-05-16 02:40 UTC, fumiama commented on plugin/qqwife/qqmapwife.go
> +	if !ok1 && !ok2 { //必须是两个单生狗
单身

2022-05-16 05:39 UTC, fumiama approved these changes

2022-05-16 05:39 UTC, merged