[fix] - 修复摸鱼日历图片问题
FloatTech/ZeroBot-Plugin pull request #251
Opened 2022-06-02 06:44 UTC by Dishesdog

修复摸鱼日历图片问题

2022-06-02 11:02 UTC, fumiama requested changes

2022-06-02 11:02 UTC, fumiama commented on plugin/moyu_calendar/calendar.go
> +	control "github.com/FloatTech/zbputils/control"
should not add this redundant `control`

2022-06-02 11:02 UTC, fumiama commented on plugin/moyu_calendar/calendar.go
> +			data, err := web.RequestDataWith(web.NewDefaultClient(), "https://api.vvhan.com/api/moyu?type=json", "GET", "", "")
web.GetData()

2022-06-02 11:02 UTC, fumiama commented on plugin/moyu_calendar/calendar.go
> +			picURL := gjson.Get(string(data), "url").String()
binary.BytesToString()

2022-06-02 11:13 UTC, Dishesdog commented on plugin/moyu_calendar/calendar.go
> +			picURL := gjson.Get(string(data), "url").String()
> binary.BytesToString()

这获取的是json结构中的图片地址

最后发送消息调用的是 ctx.SendChain(message.Image(picURL)) 直接发送图片地址

2022-06-02 11:13 UTC, Dishesdog commented on plugin/moyu_calendar/calendar.go
> +			data, err := web.RequestDataWith(web.NewDefaultClient(), "https://api.vvhan.com/api/moyu?type=json", "GET", "", "")
> web.GetData()

这获取的是接口返回的json数据

2022-06-02 11:35 UTC, fumiama commented on plugin/moyu_calendar/calendar.go
> +			data, err := web.RequestDataWith(web.NewDefaultClient(), "https://api.vvhan.com/api/moyu?type=json", "GET", "", "")
why not still use web.GetData()

2022-06-02 11:35 UTC, fumiama commented on plugin/moyu_calendar/calendar.go
> +			picURL := gjson.Get(string(data), "url").String()
replace string(data) with binary.BytesToString(data)

2022-06-06 02:33 UTC, Dishesdog commented on plugin/moyu_calendar/calendar.go
> +			picURL := gjson.Get(string(data), "url").String()
ok

2022-06-06 02:34 UTC, closed without merging