Update qqmapwife.go
FloatTech/ZeroBot-Plugin pull request #261
Opened 2022-06-11 12:57 UTC by fangliuyu

2022-06-11 15:25 UTC, fumiama requested changes
最好吧lastdate也存到数据库，否则有可能会丢失该信息从而错过重置

2022-06-11 15:25 UTC, fumiama commented on plugin/qqwife/qqmapwife.go
> +	oder := number
小心负数，应当使用append

2022-06-12 01:04 UTC, fangliuyu commented on plugin/qqwife/qqmapwife.go
> +	oder := number
修复，number在前面判断时同时将负数排除

新增lastdate的时间判断，这样就可以从数据库去判断是否需要重置

2022-06-12 13:33 UTC, fumiama requested changes

2022-06-12 13:33 UTC, fumiama commented on plugin/qqwife/qqmapwife.go
> +	err = sql.db.Pick(gidstr, &dbinfo) //获取表格更新的时间
新建一个单独表示最后更新时间的表，随机的可不一定是最新时间。如
```go
type updateinfo struct {
    Grp int64
    Time int64
}
```

2022-06-12 23:38 UTC, fangliuyu commented on plugin/qqwife/qqmapwife.go
> +	err = sql.db.Pick(gidstr, &dbinfo) //获取表格更新的时间
已完成

2022-06-13 04:07 UTC, fumiama approved these changes

2022-06-13 04:09 UTC, merged