feat：塔罗牌阵
FloatTech/ZeroBot-Plugin pull request #268
Opened 2022-06-17 11:12 UTC by shudorcl

使用`塔罗牌阵 [牌阵名]`抽取塔罗牌
不过在测试的时候测试机惨遭封号
![3_KWCASB`J}GWKIQXH5H R](https://user-images.githubusercontent.com/55676105/174286900-8c55d126-ab5d-4a0a-a497-43c4cb3442c5.png)
此外，装载塔罗牌数据的函数显得有点冗余，但一下子想不到什么比较优雅的解决方法

2022-06-17 12:35 UTC, fumiama requested changes
能否规避封号风险，比如使用图片发送？

2022-06-17 12:37 UTC, fumiama commented
> 此外，装载塔罗牌数据的函数显得有点冗余，但一下子想不到什么比较优雅的解决方法

参考其他插件，将doonceonsuccess定义为一个变量，在所有需要的地方引入，这样不论在哪都只会执行一次。有多个下载可以附加多个doonce

2022-06-18 04:05 UTC, fumiama requested changes
还需调整doonce问题

2022-06-18 04:05 UTC, fumiama commented on plugin/tarot/tarot.go
> +			ctx.SendChain(message.Image("base64://" + binary.BytesToString(b)))
message.ImageBytes(b)

2022-06-18 08:51 UTC, fumiama approved these changes

2022-06-18 08:51 UTC, merged

2022-06-18 16:18 UTC, omanikk commented
你好 塔罗牌阵报错如下 ERROR:resp body len <= 0

2022-06-18 18:04 UTC, shudorcl commented
> 你好 塔罗牌阵报错如下 ERROR:resp body len <= 0

因为zbpdata方面还没有同步，可以先行下载formation.json，放入/data/tarot中

2022-06-18 18:05 UTC, omanikk commented
收到 十分感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月19日(星期天) 凌晨2:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FloatTech/ZeroBot-Plugin] feat：塔罗牌阵 (PR #268)





  
你好 塔罗牌阵报错如下 ERROR:resp body len <= 0
  
因为zbpdata方面还没有同步，可以先行下载formation.json，放入/data/tarot中
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;

2022-06-18 18:39 UTC, omanikk commented
不好意思 我实在没有找到这个js文件 可以给个链接吗&nbsp; 麻烦了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FloatTech/ZeroBot-Plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月19日(星期天) 凌晨2:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FloatTech/ZeroBot-Plugin] feat：塔罗牌阵 (PR #268)





  
你好 塔罗牌阵报错如下 ERROR:resp body len <= 0
  
因为zbpdata方面还没有同步，可以先行下载formation.json，放入/data/tarot中
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;

2022-06-19 12:28 UTC, shudorcl commented
> 不好意思 我实在没有找到这个js文件 可以给个链接吗&nbsp; 麻烦了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "FloatTech/ZeroBot-Plugin" ***@***.***&gt;; 发送时间:&nbsp;2022年6月19日(星期天) 凌晨2:05 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [FloatTech/ZeroBot-Plugin] feat：塔罗牌阵 (PR #268) 你好 塔罗牌阵报错如下 ERROR:resp body len <= 0 因为zbpdata方面还没有同步，可以先行下载formation.json，放入/data/tarot中 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

https://github.com/FloatTech/ZeroBot-Plugin/issues/244#issuecomment-1159711900