🎨 修改bilibili,bilibiliparse插件结构，添加bilibili动态直播专栏解析
FloatTech/ZeroBot-Plugin pull request #319
Opened 2022-07-16 04:41 UTC by guohuiyuan

2022-07-19 03:22 UTC, fumiama requested changes
尽量少用gjson

2022-07-19 03:22 UTC, fumiama commented on plugin/bilibili/api.go
> +	req, err := http.NewRequest("GET", fmt.Sprintf(medalwallURL, uid), nil)
统一用getdata，要不就用json.NewDecoder

2022-07-19 03:22 UTC, fumiama commented on plugin/bilibili/api.go
> +	_ = json.Unmarshal(binary.StringToBytes(j.Get("data.list").Raw), &result)
错误尽量不要忽略

2022-07-19 03:22 UTC, fumiama commented on plugin/bilibili/api.go
> +	fmt.Println(string(data))
不要不经过logrus向控制台打印任何东西。

2022-07-19 03:22 UTC, fumiama commented on plugin/bilibili/bilibili_parse.go
> +			searchVideoRe := regexp.MustCompile(searchVideo)
全局

2022-07-19 04:47 UTC, guohuiyuan commented on plugin/bilibili/api.go
> +	req, err := http.NewRequest("GET", fmt.Sprintf(medalwallURL, uid), nil)
你得封装一个自定义header的getdata，我暂时先改成后者

2022-07-19 06:23 UTC, guohuiyuan commented on plugin/bilibili/api.go
> +	req, err := http.NewRequest("GET", fmt.Sprintf(medalwallURL, uid), nil)
这不好改，我需要定义一个新结构体

2022-07-19 11:24 UTC, fumiama commented on plugin/bilibili/api.go
> +	req, err := http.NewRequest("GET", fmt.Sprintf(medalwallURL, uid), nil)
可以

2022-07-20 06:35 UTC, fumiama requested changes
看一下报错

2022-07-20 09:19 UTC, guohuiyuan commented
> 看一下报错

这个lint有问题，gif的入参的数量不能改啊

2022-07-21 04:54 UTC, fumiama approved these changes

2022-07-21 04:54 UTC, merged