feat：将牌阵结果解析纳入转发列表
FloatTech/ZeroBot-Plugin pull request #359
Opened 2022-08-03 09:12 UTC by shudorcl

将牌阵结果解析纳入转发列表

不过怎么commit列表还是那么长。。。

2022-08-03 12:01 UTC, guohuiyuan commented
> 将牌阵结果解析纳入转发列表
> 
> 不过怎么commit列表还是那么长。。。

最用master同步上游分支-----在自己其他分支做修改pr到上游, 自己的master再去同步上游的master

2022-08-03 12:12 UTC, shudorcl commented
> 最用master同步上游分支-----在自己其他分支做修改pr到上游, 自己的master再去同步上游的master

问题正在于此，实际上这个pr一开始是打算从其他分支pr到上游的：
（在上次pr后，在GitHub网页同步上游时也选择了`discard changes`，然后再分支出去进行修改）
![image](https://user-images.githubusercontent.com/55676105/182604358-f82f46b5-aaaa-4507-b5da-0179fc32d27c.png)
但是依然出现了先前的commit
于是想尝试一下合并到fork的master能否有所改观，可惜如现在所见并没有

2022-08-03 12:16 UTC, guohuiyuan commented
你下次，然后回滚自己的master，然后同步上游master，就不会有问题了，或者删掉重新fork

2022-08-03 14:28 UTC, fumiama commented
删掉重新fork最快了

2022-08-03 14:32 UTC, fumiama requested changes

2022-08-03 14:32 UTC, fumiama commented on README.md
> + <img src="http://cmoe.azurewebsites.net/cmoe?name=ZeroBot-Plugin&theme=r34" /><br>
非必要不修改

2022-08-03 14:32 UTC, fumiama commented on plugin/tarot/tarot.go
> +			// TODO 显示塔罗牌列表，下方使用图片发出，但是图片过大
想办法缩减，不然就弄个文字的合并转发也好

2022-08-03 14:37 UTC, shudorcl commented on plugin/tarot/tarot.go
> +			// TODO 显示塔罗牌列表，下方使用图片发出，但是图片过大
计划是自己P有空一张图放到gitcode

2022-08-03 14:49 UTC, fumiama commented on plugin/tarot/tarot.go
> +			// TODO 显示塔罗牌列表，下方使用图片发出，但是图片过大
不如合并转发灵活

2022-08-03 16:17 UTC, shudorcl commented on plugin/tarot/tarot.go
> +			// TODO 显示塔罗牌列表，下方使用图片发出，但是图片过大
最后还是使用了生成图片

![image](https://user-images.githubusercontent.com/55676105/182658486-d8e0b07b-b1e2-4240-b518-f7295b6a3298.png)

2022-08-04 05:40 UTC, fumiama approved these changes

2022-08-04 05:40 UTC, merged

2022-08-04 09:04 UTC, shudorcl commented
> > 最用master同步上游分支-----在自己其他分支做修改pr到上游, 自己的master再去同步上游的master
> 
> 问题正在于此，实际上这个pr一开始是打算从其他分支pr到上游的

重新测试了一下，问题似乎是在本地的master分支。。。

2022-08-04 11:51 UTC, fumiama commented
你会高级的当然就好说了，重新fork最省事但确实不是最优解。最优解是添加一个新origin是上游，然后从上面拉取一个新分支，修改后PR。

2022-08-04 13:48 UTC, shudorcl commented
好有道理，学到了