feat: 抽塔罗牌附加解析
FloatTech/ZeroBot-Plugin pull request #383
Opened 2022-08-21 16:23 UTC by shudorcl

- 恢复了之前因为解析冗长去除的抽塔罗牌附加解析
- gif增加了支持动图的`一直`，但在处理一些gif时会出现崩坏
- 删去了api已经[失去维护三个月](https://t.bilibili.com/658607344806002729)的小作文查重

2022-08-21 16:29 UTC, shudorcl commented
`一直`出现崩坏的原因是因为一些gif内会有过度帧，但是处理的时候会一视同仁缩放。。。暂时未找到解决方案

2022-08-22 01:42 UTC, fumiama requested changes

2022-08-22 01:42 UTC, fumiama commented on plugin/gif/gif.go
> +	wg.Wait()
这wg没用，可以删了。
建议看看其他wg的用法。

2022-08-22 01:42 UTC, fumiama commented on plugin/hyaku/main.go
> +//nolint: asciicheck
以后不用改这个了

2022-08-22 01:42 UTC, fumiama commented on plugin/tarot/tarot.go
> +				message.Image(fmt.Sprintf("%s/%s/%s", bed, reverse[p], card.ImgURL)),
建议直接加起来

2022-08-22 01:42 UTC, fumiama commented on plugin/tarot/tarot.go
> +				message.Image(fmt.Sprintf("%s/%s/%s", bed, reverse[p], card.ImgURL)),
同

2022-08-22 01:44 UTC, shudorcl commented on plugin/hyaku/main.go
> +//nolint: asciicheck
这是[github-actions](https://github.com/apps/github-actions)自动加的

2022-08-22 07:19 UTC, fumiama approved these changes

2022-08-22 07:32 UTC, fumiama approved these changes

2022-08-22 07:33 UTC, merged