Feature danmakusuki
FloatTech/ZeroBot-Plugin pull request #388
Opened 2022-08-26 02:47 UTC by guohuiyuan

2022-08-26 10:49 UTC, fumiama requested changes

2022-08-26 10:49 UTC, fumiama commented on config.go
> +// package main 主函数
main包我记得不用加这个注释

2022-08-26 10:49 UTC, fumiama commented on plugin/bilibili/api.go
> +	data, err := io.ReadAll(res.Body)
既然有了 res.Body 这个 io.Reader, 就可以用 json.NewDecoder 了

2022-08-26 10:49 UTC, fumiama commented on plugin/bilibili/bilibili.go
> +	_, _ = engine.GetLazyData("bilibili.db", false)
我的建议是，不要在启动时下载不是必须下载的东西

2022-08-26 10:50 UTC, fumiama commented
记得改README

2022-08-26 11:25 UTC, guohuiyuan commented on config.go
> +// package main 主函数
现在的lint提示要加注释了

2022-08-26 15:24 UTC, guohuiyuan commented
已经改完了

2022-08-27 04:09 UTC, fumiama commented on config.go
> +// package main 主函数
怪

2022-08-27 04:11 UTC, fumiama approved these changes

2022-08-27 04:11 UTC, fumiama approved these changes

2022-08-27 04:13 UTC, merged