Optimize: 更换经常出问题的iw233接口为MoeHu
FloatTech/ZeroBot-Plugin pull request #412
Opened 2022-09-13 15:11 UTC by MoYoez

2022-09-14 08:35 UTC, fumiama requested changes
我记得这个可以直接返回图片，不再需要解析json

2022-09-16 02:16 UTC, fumiama requested changes

2022-09-16 02:16 UTC, fumiama commented on plugin/score/sign_in.go
> +	data, err := web.GetData(backgroundURL)
直接用 file.DownloadTo()

2022-09-17 02:25 UTC, fumiama requested changes

2022-09-17 02:25 UTC, fumiama commented on plugin/score/sign_in.go
> +	return os.WriteFile(picFile, []byte(picFile), 0644)
你确定理解了你的代码吗😂

2022-09-17 02:53 UTC, MoYoez commented on plugin/score/sign_in.go
> +	return os.WriteFile(picFile, []byte(picFile), 0644)
没用过这个(((

2022-09-17 02:54 UTC, fumiama commented on plugin/score/sign_in.go
> +	return os.WriteFile(picFile, []byte(picFile), 0644)
直接return err就行了

2022-09-17 03:51 UTC, fumiama requested changes

2022-09-17 03:51 UTC, fumiama commented on plugin/score/sign_in.go
>  	if err != nil {
需要吗

2022-09-17 05:43 UTC, fumiama approved these changes

2022-09-17 05:43 UTC, merged