add:百度内容审核插件
FloatTech/ZeroBot-Plugin pull request #468
Opened 2022-10-21 03:59 UTC by GenesisAN

新增百度内容审核插件，包含API配置，群配置，审核配置，审核惩罚，等功能

2022-10-22 03:51 UTC, fumiama requested changes
暂时先写这些，你可以把go.mod更新推上来了。推上来之后，可能会看到lint的更多报错，还望一并修复。

2022-10-22 03:51 UTC, fumiama commented on plugin/baidu_audit/audit.go
> +type BaiduRes struct {
API部分建议PR至AnimeAPI

2022-10-22 03:51 UTC, fumiama commented on plugin/baidu_audit/audit.go
> +type KeyConfig struct {
包内结构体与函数均用小写。下同。

2022-10-22 03:51 UTC, fumiama commented on plugin/baidu_audit/audit.go
> +		PrivateDataFolder: "baidu_audit",
所有命名无需`_`，下同。

2022-10-22 03:51 UTC, fumiama commented on plugin/baidu_audit/audit.go
> +	if configinit {
尽量避免全局变量的使用，而应该作为返回值。

2022-10-22 03:51 UTC, fumiama commented on plugin/baidu_audit/audit.go
> +	engine.OnRegex("获取BDAKey", zero.SuperUserPermission).SetBlock(true).
不是正则的，应当用`OnFullMatch`

2022-10-22 03:51 UTC, fumiama commented on plugin/baidu_audit/audit.go
> +func BTS(b bool) string {
建议参考

https://github.com/FloatTech/zbpctrl/blob/4834c691151192774356af77e96f1d504812c6b5/enable.go#L1-L17

2022-10-22 03:51 UTC, fumiama commented on plugin/baidu_audit/audit.go
> +	engine.OnRegex("^设置(不?)检测类型([01234567])$", zero.AdminPermission, ClientCheck).SetBlock(true).
应当用`(不)?`

2022-10-22 03:51 UTC, fumiama commented on plugin/baidu_audit/audit.go
> +	engine.OnRegex("^配置BDAKey (.*) (.*)", zero.SuperUserPermission).SetBlock(true).
`^配置BDAKey\s*(.*)\s*(.*)$`

2022-10-22 03:51 UTC, fumiama commented on plugin/baidu_audit/audit.go
> +		if ok {
不要叠金字塔，而应当使用其反面，如
```go
if !ok || !group.Enable {
    return
}
var urls = []string{}
......
```

2022-10-22 03:51 UTC, fumiama commented on plugin/baidu_audit/audit.go
> +	engine.OnPrefix("^文本检测", ClientCheck).SetBlock(false).
这个`^`是否画风不符

2022-10-22 03:51 UTC, fumiama commented on plugin/baidu_audit/audit.go
> +		group = Group{false, true, true, false, false, false, false, 1, 60, 1, [8]bool{}, map[int64]AuditHistory{}}
为false的，为空的，均可不填。当然map是需要的。

2022-10-22 03:51 UTC, fumiama commented on plugin/baidu_audit/audit.go
> +func (group Group) GetUsder(userID int64) AuditHistory {
func (group *Group)

2022-10-22 03:51 UTC, fumiama commented on plugin/baidu_audit/audit.go
> +	} else {
redundant else，其他位置同理

2022-10-22 03:51 UTC, fumiama commented on plugin/baidu_audit/audit.go
> +	if isExist(configPath) {
使用file.IsExist()

2022-10-22 03:51 UTC, fumiama commented on plugin/baidu_audit/audit.go
> +func JsonSave(v interface{}, path string) (bool, error) {
不要使用interface{}

2022-10-22 03:51 UTC, fumiama commented on plugin/baidu_audit/audit.go
> +	file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0666)
使用json.NewEncoder(file).Encode()

2022-10-22 03:51 UTC, fumiama commented on plugin/baidu_audit/audit.go
> +	writer := bufio.NewWriter(file)
不需要的操作

2022-10-22 03:51 UTC, fumiama commented on plugin/baidu_audit/audit.go
> +	var msgs []message.MessageSegment
金字塔，下略。

2022-10-22 03:51 UTC, fumiama commented on plugin/baidu_audit/audit.go
> +	err := json.Unmarshal([]byte(resjson), &bdres)
使用binary.StringToBytes()

2022-10-23 04:49 UTC, GenesisAN commented on plugin/baidu_audit/audit.go
> +type BaiduRes struct {
这个这只有一个数据结构，API是官方自带的go SDK，就一个登陆方法，一个发送消息获取审核结果，封装后反而增加了复杂性。所以就不再单独拎出来了

2022-10-23 15:44 UTC, GenesisAN commented
已修复大部分问题，就是提交的有点多了XD

2022-10-24 15:34 UTC, fumiama requested changes

2022-10-24 15:34 UTC, fumiama commented on README.md
> +</details>
README顺序应保持与main.go中一致

2022-10-24 15:34 UTC, fumiama commented on plugin/baiduaudit/audit.go
> +func (group *group) getUsder(userID int64) auditHistory {
typo

2022-10-24 15:34 UTC, fumiama commented on plugin/baiduaudit/audit.go
> +	Enable             EnableMark             //是否启用内容审核
所有注释都应在双斜线后空一格，如`// 123`

2022-10-25 10:43 UTC, fumiama approved these changes

2022-10-25 10:43 UTC, merged