✨ 添加qq空间表白墙
FloatTech/ZeroBot-Plugin pull request #489
Opened 2022-11-06 10:51 UTC by guohuiyuan

2022-11-06 11:30 UTC, fumiama requested changes
请先移除对goja和requests的依赖，这两个应该是不必要的，会大幅增加程序大小。

2022-11-06 11:33 UTC, fumiama requested changes

2022-11-06 11:33 UTC, fumiama commented on plugin/qzone/types.go
> +package qzone
应移动至qzone库

2022-11-12 09:28 UTC, guohuiyuan commented on plugin/qzone/types.go
> +package qzone
已修改

2022-11-13 10:03 UTC, fumiama approved these changes

2022-11-13 10:03 UTC, merged