Feature dress 20221204
FloatTech/ZeroBot-Plugin pull request #514
Opened 2022-12-04 08:27 UTC by guohuiyuan

2022-12-04 10:36 UTC, fumiama requested changes

2022-12-04 10:36 UTC, fumiama commented on plugin/dress/api.go
> +	dressList = make([]string, 0)
dressList = make([]string, `gjson获得的具体长度`)

2022-12-04 14:32 UTC, guohuiyuan commented on plugin/dress/api.go
> +	dressList = make([]string, 0)
已修改

2022-12-05 03:24 UTC, fumiama requested changes

2022-12-05 03:24 UTC, fumiama commented on plugin/dress/api.go
> +	dressList = make([]string, 0, int(gj.Get("@this.#").Int()))
建议用
```go
arr := gjson.ParseBytes(data).Get("@this").Array()
dressList = make([]string, len(arr))
for i, v := range arr {
    dressList[i] = v.String()
}
```

2022-12-05 03:33 UTC, fumiama approved these changes

2022-12-05 03:33 UTC, fumiama approved these changes

2022-12-05 03:34 UTC, merged