fix: aireply: ent->enr & update README & optimize bilibili match
FloatTech/ZeroBot-Plugin pull request #519
Opened 2022-12-07 15:43 UTC by shudorcl

2022-12-08 02:29 UTC, fumiama requested changes

2022-12-08 11:58 UTC, shudorcl commented on plugin/ai_reply/main.go
> +	chatgptfile := enr.DataFolder() + "chatgpt.txt"
这样结构不是更清晰一些嘛

2022-12-08 15:22 UTC, fumiama commented on plugin/ai_reply/main.go
> +	chatgptfile := enr.DataFolder() + "chatgpt.txt"
我要直观看到你改了哪些，结构都一样混乱，放哪无所谓。

2022-12-09 10:24 UTC, guohuiyuan commented
gkd,顶不住了

2022-12-09 15:23 UTC, fumiama approved these changes

2022-12-09 15:23 UTC, merged