群聊中撤回消息
FloatTech/ZeroBot-Plugin pull request #520
Opened 2022-12-09 11:15 UTC by jinyunboss

群聊中直接回复需要撤回的消息来进行撤回,如果机器人权限足够的话,可以把请求撤回的消息一并撤回

2022-12-09 15:26 UTC, fumiama requested changes

2022-12-09 15:26 UTC, fumiama commented on plugin/manager/manager.go
> +		Handle(func(ctx *zero.Ctx) {
不要无故打印log

2022-12-09 15:26 UTC, fumiama commented on plugin/manager/manager.go
> +			go func(i message.MessageID) {
没有意义，底层仍然是同步发送。请移除所有go。

2022-12-09 15:26 UTC, fumiama commented on plugin/manager/manager.go
> +			}(message.NewMessageIDFromInteger(ctx.Event.MessageID.(int64)))
对于请求撤回的消息，由发送者自行决定是否撤回。何况bot不是管理员的情况下，也无法撤回别人的消息。

2022-12-10 02:39 UTC, jinyunboss commented on plugin/manager/manager.go
> +			}(message.NewMessageIDFromInteger(ctx.Event.MessageID.(int64)))
因为是回复原消息进行撤回，如果不把请求撤回的消息一并撤回，那么请求撤回的消息中还是能看到撤回的消息内容

2022-12-10 02:49 UTC, jinyunboss commented on plugin/manager/manager.go
> +			//ctx.DeleteMessage(message.NewMessageIDFromInteger(ctx.Event.MessageID.(int64)))
大部分情况下，bot都不会是群主，只撤回回复的消息， 请求撤回的消息在bot和请求人都是管理员的情况下，没办法撤回

2022-12-10 05:59 UTC, fumiama approved these changes

2022-12-10 06:11 UTC, merged