add WarframeAPI
FloatTech/ZeroBot-Plugin pull request #541
Opened 2022-12-23 02:21 UTC by GenesisAN

新增星际战甲国际服的游戏查询API

2022-12-23 15:09 UTC, fumiama requested changes
先这些吧，问题较大，慢慢改着。

2022-12-23 15:09 UTC, fumiama commented on plugin/warframeapi/main.go
> +	eng.OnRegex(`^.wm (.*)$`).SetBlock(true).
prefix

2022-12-23 15:09 UTC, fumiama commented on plugin/warframeapi/main.go
> +	data, err := json.Marshal(v)
```go
f, err := os.Create(...)
defer f.Close()
err = json.NewEncoder(f).Encode(v)
```
结束。不用你那样磨磨叽叽的。

2022-12-23 15:09 UTC, fumiama commented on plugin/warframeapi/main.go
> +func isExist(path string) bool {
用file.IsExist()/IsNotExist()

2022-12-23 15:09 UTC, fumiama commented on plugin/warframeapi/main.go
> +func getData(url string, head []string, headvalue []string) (data []byte, err error) {
用个map

2023-01-05 03:45 UTC, fumiama requested changes
我来教你一个小技巧：点进`Files Changed`，看到那些红黄框框了吗，修复它们。

2023-01-05 03:45 UTC, fumiama commented on plugin/warframeapi/gametime.go
> +	rwm.RUnlock()
你这不等着死锁吗，上面那个返回了可没解锁哦。建议使用
```go
defer rwm.RUnlock()
```
下同。

2023-01-05 03:45 UTC, fumiama commented on plugin/warframeapi/gametime.go
> +	rwm.RLock()
这种和gameTime本身关联的🔒，是不是不应该是全局变量，而是gameTime的一个属性？

2023-01-05 03:45 UTC, fumiama commented on plugin/warframeapi/main.go
> +	ctx           *zero.Ctx          //BOT实例
很坏的实现，建议移除之。

2023-01-05 03:45 UTC, fumiama commented on plugin/warframeapi/main.go
> +	client        http.Client        //发起http请求的client实例
再说一遍，尽量减少全局变量的个数。这玩意不是单片机，没必要。

2023-01-05 03:45 UTC, fumiama commented on plugin/warframeapi/main.go
> +		PrivateDataFolder: "warframeAPI",
全小写。

2023-01-05 12:17 UTC, GenesisAN commented on plugin/warframeapi/main.go
> +	eng.OnRegex(`^(.*)平原状态$`).SetBlock(true).
如果使用后缀匹配触发的话，xx平原状态的xx如何获取？

2023-01-05 12:37 UTC, GenesisAN commented on plugin/warframeapi/main.go
> +	eng.OnRegex(`^(.*)平原状态$`).SetBlock(true).
看了眼源码，明白了，后缀匹配后会把剩余的参数传入args里，妙啊

2023-01-05 12:45 UTC, GenesisAN commented on plugin/warframeapi/main.go
> +	updateWM()
已解决，已改为通过返回值来获取wfapi

2023-01-05 12:45 UTC, GenesisAN commented on plugin/warframeapi/gametime.go
> +	rwm.RUnlock()
姑且改了，但不清楚对不对XD

2023-01-05 12:46 UTC, GenesisAN commented on plugin/warframeapi/gametime.go
> +	rwm.RLock()
已加入gameTime属性中，但不确定有没有其他我没发现的问题

2023-01-05 12:46 UTC, GenesisAN commented on plugin/warframeapi/main.go
> +	ctx           *zero.Ctx          //BOT实例
已移除，待后续更新追加修复

2023-01-05 12:59 UTC, GenesisAN commented on plugin/warframeapi/main.go
> +	client        http.Client        //发起http请求的client实例
已解决，当初加这个是图开发方便个人自用，这些值实际上每次使用都是用新的，全局变量确实无意义

2023-01-06 02:03 UTC, GenesisAN commented on plugin/warframeapi/main.go
> +	next := zero.NewFutureEvent("message", 999, false, ctx.CheckSession()).Next()
这个函数对goto行为进行了重写，如果没啥问题，我将对所有类似goto行为的地方进行替换

2023-01-10 11:03 UTC, fumiama commented on plugin/warframeapi/main.go
> +	return message.Image("base64://" + binary.BytesToString(b))
ImageBytes

2023-01-10 11:04 UTC, fumiama commented on plugin/warframeapi/main.go
> +func getData(url string, head map[string]string) (data []byte, err error) {
请用web.RequestDataWithHeaders

2023-01-31 04:59 UTC, GenesisAN commented
目前未改进问题：
1.平原时间的锁问题
2.stringArrayToImage函数里面，不能直接使用ImageBytes，必须要用Image
因为ImageBytes是放入byte数组然后转base64，而 text.RenderToBase64出来的就已经是base64的String了，再放入会再多转一次base64

2023-01-31 08:22 UTC, fumiama approved these changes

2023-01-31 08:22 UTC, merged