给aifalse加一点细节
FloatTech/ZeroBot-Plugin pull request #575
Opened 2023-02-01 17:11 UTC by Jiang-Red

2023-02-02 03:36 UTC, fumiama requested changes

2023-02-02 03:36 UTC, fumiama commented on plugin/ai_false/ai_false.go
> +	url, err := bilibili.GetRealURL(backgroundURL)
坏了，为啥要用bilibili

2023-02-02 03:36 UTC, fumiama commented on plugin/ai_false/ai_false.go
> +var boottime time.Time
```go
var boottime = time.Now()
```

2023-02-02 03:36 UTC, fumiama commented on plugin/ai_false/ai_false.go
> +				ctx.SendChain(message.Text("ERROR:", err))
"`ERROR: `", err

2023-02-02 03:36 UTC, fumiama commented on plugin/ai_false/ai_false.go
> +				ctx.SendChain(message.Text("ERROR:可能被风控了"))
"ERROR: 可能..."

2023-02-02 03:36 UTC, fumiama commented on plugin/ai_false/ai_false.go
> +	titlecard := gg.NewContext(canvas.W()-70-70, 250)
这些声明也可移入go

2023-02-02 03:36 UTC, fumiama commented on plugin/ai_false/ai_false.go
> +	canvas.DrawImage(shadowimg, 0, 0)
全部都需要判空

2023-02-02 03:36 UTC, fumiama commented on plugin/ai_false/ai_false.go
> +	return sendimg, nil
哦，这是不行的，cl必须在使用后执行，在使用前执行可能导致数据错误。

2023-02-02 03:36 UTC, fumiama commented on plugin/ai_false/ai_false.go
> +	stateinfo = make([]*status, 3)
既然固定是3，那么直接 [3]*status 即可。

2023-02-02 03:36 UTC, fumiama commented on plugin/ai_false/ai_false.go
> +		m.Manager.ForEach(func(key string, manager *ctrl.Control[*zero.Ctx]) bool {
很难说是一个好的实现。你可使用
```go
len(m.Manager.M)
```

2023-02-02 03:36 UTC, fumiama commented on plugin/ai_false/ai_false.go
> +	m, ok := control.Lookup("aifalse")
既然是内部调用，你可以直接传入m。m可通过ctx.States获取。

2023-02-02 15:43 UTC, Jiang-Red commented on plugin/ai_false/ai_false.go
> +	url, err := bilibili.GetRealURL(backgroundURL)
因为要获取跳转后的链接，所以用了这个函数，也许这个函数应该放到`floatbox/web`里去

2023-02-04 04:20 UTC, fumiama requested changes
另外，刚才出现了冲突，需要解决一下。

2023-02-04 04:20 UTC, fumiama commented on plugin/ai_false/ai_false.go
> +			m, ok := ctx.State["manager"].(*ctrl.Control[*zero.Ctx])
这个判断不可能为不ok，可以不写。

2023-02-04 04:20 UTC, fumiama commented on plugin/ai_false/ai_false.go
> +			_, err := file.GetLazyData(text.GlowSansFontFile, control.Md5File, true)
目前可以就这样，但是你可以找找直接将下好的data导入LoadFontFace的方式，比如在zbp新建一个修改版的gg。导入方法可参考我修改的jieba。鉴于gg本身已很久未更新，就不考虑PR回原仓库了。

2023-02-04 04:20 UTC, fumiama commented on plugin/ai_false/ai_false.go
> +	url, err := bilibili.GetRealURL(backgroundURL)
可以，我之后移动。

2023-02-05 04:58 UTC, fumiama approved these changes

2023-02-05 04:59 UTC, merged