支持Go 1.20
FloatTech/ZeroBot-Plugin pull request #577
Opened 2023-02-02 23:55 UTC by icarus-ai

2023-02-03 04:09 UTC, icarus-ai commented
go 1.20不设置随机数种子

`package main
import (
    "fmt"
    "math/rand"
)
func main() {
    fmt.Println(rand.Int31())
    fmt.Println(rand.Int31())
}
`
单独运行上面这个三次 每次输出结果都不一样 如果是go1.20 main.go 里的rand.Seed()能否删除?

2023-02-04 03:43 UTC, fumiama requested changes
关于rand一事，要知道并非所有人编译时都在用1.20，所以应当搞一个条件编译。但是这样又太麻烦了，所以这次PR你可以不用管。

2023-02-04 03:43 UTC, fumiama commented on .github/workflows/nightly.yml
> +          go-version: '1.19'
可以，不过不要做这个无意义的改动。

2023-02-04 03:52 UTC, icarus-ai commented on .github/workflows/nightly.yml
> +          go-version: '1.19'
> 可以，不过不要做这个无意义的改动。

这地方是忘了改回原样，之前改成不带单引号的1.20，被github按数字处理了(1.2)😓

2023-02-04 04:02 UTC, icarus-ai commented
> 关于rand一事，要知道并非所有人编译时都在用1.20，所以应当搞一个条件编译。但是这样又太麻烦了，所以这次PR你可以不用管。

好的

2023-02-04 04:03 UTC, fumiama commented
额，也没让你关啊，我的意思是你可以不用管删rand那句。

2023-02-04 04:03 UTC, fumiama approved these changes

2023-02-04 04:05 UTC, merged