⭐新设计的签到
FloatTech/ZeroBot-Plugin pull request #587
Opened 2023-02-16 02:42 UTC by MoYoez

2023-02-16 09:21 UTC, fumiama requested changes

2023-02-16 09:21 UTC, fumiama commented on plugin/score/sign_in.go
> +			data, err := web.GetData("http://q4.qlogo.cn/g?b=qq&nk=" + strconv.FormatInt(uid, 10) + "&s=640")
获取图片可与画图同步进行。

2023-02-16 09:21 UTC, fumiama commented on plugin/score/sign_in.go
> +			if err != nil {
err判断要紧跟GetData，同时记得向用户发送报错。

2023-02-16 09:21 UTC, fumiama commented on plugin/score/sign_in.go
> +				ctx.SendChain(message.Text("ERROR: ", err))
要输出报错就在所有有err的位置输出，否则就都不要输出。

2023-02-16 09:21 UTC, fumiama commented on plugin/score/sign_in.go
>  				log.Errorln("[score]", err)
虽然不是你写的，但是这里没必要打印出来，又没人看。

2023-02-16 11:55 UTC, fumiama requested changes

2023-02-16 11:55 UTC, fumiama commented on plugin/score/sign_in.go
> +				ctx.SendChain(message.Text("ERROR: ", err))
这里不需要输出err吧，你看懂代码了吗

2023-02-16 11:57 UTC, fumiama commented
另外这是想干什么，不要改动无关位置。
![屏幕快照 2023-02-16 下午7 56 33](https://user-images.githubusercontent.com/41315874/219358687-5e744ead-d63f-486d-9e4a-b3a2f84f3842.png)

2023-02-16 12:26 UTC, MoYoez commented
oki了 估计是昨晚debug图方便就直接一次性删掉data文件夹的缘故(

2023-02-17 05:03 UTC, fumiama approved these changes
perfect.

2023-02-17 05:03 UTC, merged