Feature gui 20230219
FloatTech/ZeroBot-Plugin pull request #597
Opened 2023-02-23 14:43 UTC by guohuiyuan

2023-02-25 09:03 UTC, fumiama requested changes
webui不安全，我建议默认不监听，收到某些指令后再监听，还可以关闭监听。

2023-02-25 09:25 UTC, guohuiyuan commented
> webui不安全，我建议默认不监听，收到某些指令后再监听，还可以关闭监听。

问题来了，假如重复收到启动指令怎么办

2023-02-25 09:33 UTC, fumiama commented
这不是问题，随便什么方法都可以确保只有一次。就算什么都不做，你在第二次监听时也会失败，因为端口被占用。

2023-03-07 16:26 UTC, fumiama requested changes

2023-03-07 16:26 UTC, fumiama commented on main.go
> +	webctrl "github.com/FloatTech/zbputils/control/web"
把它放到最下面的内置依赖

2023-03-07 16:26 UTC, fumiama commented on README.md
> +> webui持续开发中, 环境加入[ZeroBot-Plugin-Webui](https://github.com/guohuiyuan/ZeroBot-Plugin-Webui)
错字受

2023-03-07 16:26 UTC, fumiama commented on README.md
> +- **-g url**: 设置`webuiUrl`，默认为`127.0.0.1:3000`
别驼峰啊

2023-03-07 16:26 UTC, fumiama commented on main.go
> +	g := flag.String("g", "127.0.0.1:3000", "Set Url of webui.")
别驼峰

2023-03-07 16:33 UTC, guohuiyuan commented on README.md
> +- **-g url**: 设置`webuiUrl`，默认为`127.0.0.1:3000`
。

2023-03-07 16:44 UTC, fumiama approved these changes

2023-03-07 16:44 UTC, merged