fix 初始化未能获取数据的问题
FloatTech/ZeroBot-Plugin pull request #602
Opened 2023-03-01 14:43 UTC by GenesisAN

2023-03-01 14:52 UTC, fumiama requested changes

2023-03-01 14:52 UTC, fumiama commented on plugin/warframeapi/api.go
> +		wmitems, itemNames, err = newwm()
要加锁防止并发

2023-03-03 14:56 UTC, GenesisAN commented on plugin/warframeapi/api.go
> +		wmitems, itemNames, err = newwm()
已添加，请帮忙看看加的有没有什么问题！

2023-03-04 05:58 UTC, fumiama requested changes
我建议把锁做成全局变量，不用和wm放一起。

2023-03-04 05:58 UTC, fumiama commented on plugin/warframeapi/api.go
> +		wd, err = newwm()
这不会造成锁状态被覆盖吗？

2023-03-04 10:16 UTC, GenesisAN commented on plugin/warframeapi/api.go
> +		wd, err = newwm()
我去，确实如此

2023-03-04 11:54 UTC, fumiama approved these changes

2023-03-04 11:54 UTC, merged