feat: steam plugin
FloatTech/ZeroBot-Plugin pull request #621
Opened 2023-03-15 15:36 UTC by Jiang-Red

2023-03-16 10:59 UTC, fumiama requested changes

2023-03-16 10:59 UTC, fumiama commented on plugin/steam/steam.go
> +		_, err := file.GetLazyData(text.FontFile, control.Md5File, true)
text.RenderToBase64 自带 GetLazy, 无需手动管理。

2023-03-16 10:59 UTC, fumiama commented on plugin/steam/steam.go
> +		if sb.String() == " 查询steam用户绑定成功, 该群绑定的用户有: \n" {
不好。建议用Len之类判断一下或整个标志变量。

2023-03-16 10:59 UTC, fumiama commented on plugin/steam/store.go
> +	sync.RWMutex
Mutex一般放在最开头，以免出现对齐问题。在这里db可不用指针，少一步初始化。

2023-03-16 10:59 UTC, fumiama commented on plugin/steam/store.go
> +	SteamID       string `json:"steam_id"`        // 绑定用户标识ID
id是数字吧，那就用int，以免注入，虽然要转换一下麻烦了点。

2023-03-16 10:59 UTC, fumiama commented on plugin/steam/store.go
> +	GameID        string `json:"game_id"`         // 游戏ID
所有是数字的都用数字，切勿偷懒。

2023-03-16 10:59 UTC, fumiama commented on plugin/steam/store.go
> +	}
dbinfos = make(...)

2023-03-16 10:59 UTC, fumiama commented on plugin/steam/listenter.go
> +		localPlayerMap := make(map[string]player)
map[string]*player

2023-03-16 10:59 UTC, fumiama commented on plugin/steam/listenter.go
> +			msg := make(message.Message, 0)
msg放循环外面，可以先分配大一点
```go
msg := make(message.Message, 0, len(playerStatus))
```
然后在每次循环开头清空
```go
msg = msg[:0]
```

2023-03-16 10:59 UTC, fumiama commented on plugin/steam/listenter.go
> +	engine.OnFullMatch("拉取steam订阅", getDB).SetBlock(true).Handle(func(ctx *zero.Ctx) {
这个耗时较长，建议加一个反并发。

2023-03-16 10:59 UTC, fumiama commented on plugin/steam/listenter.go
> +	players := make([]*player, 0)
make([]*player, 0, len(streamIds))

2023-03-16 10:59 UTC, fumiama commented on plugin/steam/listenter.go
> +func getPlayerStatus(streamIds []string) ([]*player, error) {
func getPlayerStatus(streamIds ...string)

2023-03-16 15:06 UTC, Jiang-Red commented on plugin/steam/store.go
> +	SteamID       string `json:"steam_id"`        // 绑定用户标识ID
steamid和gameid api返回的都是string

2023-03-16 15:07 UTC, Jiang-Red commented on plugin/steam/store.go
> +	SteamID       string `json:"steam_id"`        // 绑定用户标识ID
哦，我弄错了，我改改

2023-03-16 16:35 UTC, Jiang-Red commented on plugin/steam/store.go
> +	sync.RWMutex
我试了下，不`database = &streamDB{db: sql.Sqlite{}}`不会新建db文件，所以就没动

2023-03-17 05:37 UTC, fumiama requested changes

2023-03-17 05:37 UTC, fumiama commented on plugin/steam/store.go
> +	sync.RWMutex
有没有一种可能，你可以
```go
var (
    database streamDB
)
```

2023-03-17 05:37 UTC, fumiama commented on plugin/steam/listenter.go
> +	logrus.Debugln("[steamstatus] getPlayerStatus url:", url)
把这些log去了吧

2023-03-17 16:30 UTC, fumiama approved these changes

2023-03-17 16:30 UTC, merged