增加签到预设切换
FloatTech/ZeroBot-Plugin pull request #634
Opened 2023-03-22 12:33 UTC by lianhong2758

准备被源酱暴打惹

2023-03-22 12:47 UTC, fumiama requested changes

2023-03-22 12:47 UTC, fumiama commented on plugin/score/model.go
> +type scoData struct {
sco是啥，死扣？

2023-03-22 12:47 UTC, fumiama commented on plugin/score/sign_in.go
> +	defKeyID  int64 = -6
const

2023-03-22 12:47 UTC, fumiama commented on plugin/score/sign_in.go
> +		if gid <= 0 {
<0

2023-03-22 12:47 UTC, fumiama commented on plugin/score/sign_in.go
> +			err := m.Manager.SetExtra(func(s string) int64 {
别用无意义的闭包

2023-03-22 12:47 UTC, fumiama commented on plugin/score/sign_in.go
> +		if ctx.State["regex_matched"].([]string)[2] != "" {
```go
if ctx.State["regex_matched"].([]string)[2] == "" {
    ctx.SendChain(message.Text("设置失败,数据为空"))
    return
}
```

2023-03-22 12:47 UTC, fumiama commented on plugin/score/model.go
> +	drawedFile string
别用驼峰，全小写

2023-03-23 07:43 UTC, fumiama requested changes
别守着你那闭包了🤣👉

2023-03-23 14:58 UTC, fumiama requested changes

2023-03-24 16:29 UTC, lianhong2758 reviewed
i belive don't have bug.

2023-03-25 03:05 UTC, fumiama approved these changes

2023-03-25 03:06 UTC, merged