integration HowToCook function
FloatTech/ZeroBot-Plugin pull request #650
Opened 2023-04-02 11:18 UTC by sunist-c

这个PR新增了一个插件：

程序员做饭指南(Anduin2017/HowToCook)集成

1. 目前采用力大砖飞的手解markdowwn版本，如果菜谱作者不讲武德按照原项目规范写作，最后的效果就会很炸裂
2. 没有加入数据同步机制，需要手动将Anduin2017/HowToCook仓库克隆：
  ```shell
  git clone https://github.com/Anduin2017/HowToCook /path/to/data/Dish
  ```

增加了「随机菜谱」和「怎么做XXX」两个指令

2023-04-02 12:10 UTC, fumiama requested changes
> 1. 目前采用力大砖飞的手解markdown版本，如果菜谱作者不讲武德不按照原项目规范写作，最后的效果就会很炸裂

使用数据库，上传到zbpdata。至于md，我建议原样输出。或者你可以找一个渲染md的API。

> 2. 没有加入数据同步机制，需要手动将Anduin2017/HowToCook仓库克隆

上传到zbpdata并将GetLazyData的第二个参数设置为true，即可畅享同步功能。

2023-04-02 13:51 UTC, sunist-c commented
已修改，但zbpdata还未同步

2023-04-03 03:01 UTC, fumiama requested changes
你可以向zbpdata PR这个db，就可以看见效果了。

2023-04-03 03:01 UTC, fumiama commented on plugin/dish/dish.go
> +	if _, err := en.GetLazyData("dishes.db", true); err != nil {
默认值就是false。考虑反过来写，全部成功赋true。

2023-04-03 03:01 UTC, fumiama commented on plugin/dish/dish.go
> +		if err := db.Find("dishes", &d, "WHERE name = '"+dishName+"'"); err != nil {
有sql注入风险。

2023-04-04 03:09 UTC, sunist-c commented on plugin/dish/dish.go
> +	if _, err := en.GetLazyData("dishes.db", true); err != nil {
已修改

2023-04-04 03:10 UTC, sunist-c commented on plugin/dish/dish.go
> +		if err := db.Find("dishes", &d, "WHERE name = '"+dishName+"'"); err != nil {
已对查询内容进行转义处理，解决SQL注入问题

2023-04-04 03:11 UTC, sunist-c commented on plugin/dish/dish.go
> +	healthy = false
已更名为initialized

2023-04-04 11:19 UTC, fumiama requested changes
你zbpdata呢，没见你PR啊，位置在这里 https://github.com/FloatTech/zbpdata

2023-04-04 11:19 UTC, fumiama commented on plugin/dish/dish.go
> +		if err := db.Find("dishes", &d, fmt.Sprintf("WHERE name = %s", sqlPrepare(dishName))); err != nil {
可以用`name like %菜名%`做一个简单的模糊匹配

2023-04-05 07:35 UTC, sunist-c commented on plugin/dish/dish.go
> +func sqlPrepare(source string) (dest string) {
已修改

2023-04-05 07:35 UTC, sunist-c commented on plugin/dish/dish.go
> +		if err := db.Find("dishes", &d, fmt.Sprintf("WHERE name = %s", sqlPrepare(dishName))); err != nil {
已完成

2023-04-05 07:35 UTC, sunist-c commented
已提交PR

2023-04-06 05:37 UTC, fumiama requested changes

2023-04-06 05:37 UTC, fumiama commented on plugin/dish/dish.go
> +		if strings.Contains(dishName, "'") || strings.Contains(dishName, "\"") || strings.Contains(dishName, "\\") {
;也要防

2023-04-06 05:37 UTC, fumiama commented on plugin/dish/dish.go
> +			ctx.SendChain(message.Text("不合法的输入"))
return

2023-04-06 05:37 UTC, fumiama commented on plugin/dish/dish.go
> +			var d dish
drop else

2023-04-06 05:37 UTC, fumiama commented on plugin/dish/dish.go
> +				ctx.SendChain(message.Text(fmt.Sprintf("未能为客官%s找到%s的做法qwq", name, dishName)))
return

2023-04-06 05:37 UTC, fumiama commented on plugin/dish/dish.go
> +				ctx.SendChain(message.Text(fmt.Sprintf(
drop else

2023-04-06 05:37 UTC, fumiama commented on plugin/dish/dish.go
> +	} else if count, countErr := db.Count("dishes"); countErr != nil {
都err就行了

2023-04-06 05:37 UTC, fumiama commented on plugin/dish/dish.go
> +		dishName := ctx.State["args"].(string)
```go
if dishName == "" {
    return
}
```

2023-04-06 10:13 UTC, sunist-c commented
已按change request修改

2023-04-06 11:13 UTC, fumiama requested changes
可以了。请一并添加README.md与main.go。注意README中的位置要与main.go一致。

2023-04-06 11:24 UTC, sunist-c commented
已为dish插件更新readme和main.go

2023-04-06 11:28 UTC, fumiama approved these changes

2023-04-06 11:28 UTC, merged