✨ 添加据意查句
FloatTech/ZeroBot-Plugin pull request #660
Opened 2023-04-09 12:31 UTC by guohuiyuan

2023-04-11 03:55 UTC, fumiama requested changes

2023-04-11 03:55 UTC, fumiama commented on plugin/wantquotes/wantquotes.go
> +	typeList = []string{"现", "现-名言", "现-佳句", "现-佳句-文学", "现-佳句-诗歌", "现-佳句-其他", "现-网络", "现-台词", "现-台词-影视剧", "现-台词-动漫", "现-台词-综艺",
[...]string

2023-04-11 03:55 UTC, fumiama commented on plugin/wantquotes/wantquotes.go
> +	_ = m.GetExtra(&apikey)
要使用m.GetExtra，需要在options中增加Extra声明。详见其他插件。

2023-04-11 03:55 UTC, fumiama commented on plugin/wantquotes/wantquotes.go
> +func setAPIKey(m *ctrl.Control[*zero.Ctx], apikey string) error {
这两个函数已经如此之短，我的建议是不要用了，直接写进调用者。

2023-04-11 03:55 UTC, fumiama commented on plugin/wantquotes/wantquotes.go
> +		apiURL := fmt.Sprintf("%s?query=%s&type=%s&unionid=%s&secret=%s", wantquotesURL+semantic, url.QueryEscape(keyword), url.QueryEscape(quotesType), url.QueryEscape(unionid), url.QueryEscape(secret))
把这个也写进const

2023-04-11 03:55 UTC, fumiama commented on plugin/wantquotes/wantquotes.go
> +		for {
for ... sleep 结构，我建议用 time.NewTicker

2023-04-12 06:04 UTC, fumiama commented on plugin/wantquotes/wantquotes.go
> +		_ = manager.GetExtra(&key)
没有失败判断吗？

2023-04-12 06:05 UTC, fumiama commented on plugin/wantquotes/wantquotes.go
> +			time.Sleep(120 * time.Second) // 等待120秒后关闭定时器
这个实现不好。直接一个变量，每触发一次加一，结束时Stop()。

2023-04-12 06:06 UTC, fumiama commented on plugin/wantquotes/wantquotes.go
> +			select {
这样，就不用select了。

2023-04-16 15:55 UTC, Jiang-Red commented on plugin/wantquotes/wantquotes.go
> +			_ = now
这里可以这样写吧
```go
for range ticker.C {...}
```

2023-04-17 03:22 UTC, fumiama approved these changes

2023-04-17 03:23 UTC, merged