♿️ gif改为使用base64发送
FloatTech/ZeroBot-Plugin pull request #664
Opened 2023-04-12 10:21 UTC by GenesisAN

解决BOT和gocq不在同一个服务器的时候，生成的gif文件发送问题

2023-04-13 03:59 UTC, fumiama requested changes

2023-04-13 03:59 UTC, fumiama commented on plugin/gif/context.go
> +func encodeGIFToBase64(name string, gifImage *gif.GIF) (string, error) {
加到 https://github.com/FloatTech/imgfactory/blob/main/writer.go

2023-04-17 01:09 UTC, GenesisAN commented
https://github.com/FloatTech/imgfactory这个不add tag 发个版本，好像是用不了那个添加进去的新函数吧。

2023-04-17 03:29 UTC, fumiama commented
运行
```bash
go get -d github.com/FloatTech/imgfactory@main && go mod tidy
```
即可

2023-04-17 04:39 UTC, fumiama approved these changes

2023-04-17 04:40 UTC, merged