add kokomi
FloatTech/ZeroBot-Plugin pull request #679
Opened 2023-04-23 15:53 UTC by lianhong2758

估计要好几天写完

2023-04-24 12:05 UTC, fumiama requested changes
🤣👉莲宝不要滥用http status code，乖乖用json返回数据不好吗

2023-04-24 12:05 UTC, fumiama commented on plugin/kokomi/kokomi.go
> +		ctx.SendChain(message.Text(string(body)))
就这？`string(body)`搞得像第一天用zbp一样🤣👉

2023-04-25 10:04 UTC, lianhong2758 commented
> 🤣👉莲宝不要滥用http status code，乖乖用json返回数据不好吗

好思路

2023-04-25 13:58 UTC, fumiama requested changes

2023-05-02 10:35 UTC, closed without merging