fix bilibili
FloatTech/ZeroBot-Plugin pull request #710
Opened 2023-08-02 09:27 UTC by lianhong2758

2023-08-03 03:44 UTC, fumiama requested changes
莲宝比之前让人血压平稳了一些，但仍需继续努力

2023-08-03 03:44 UTC, fumiama commented on plugin/bilibili/bilibilipush.go
> +	mixinKeyEncTab = []int{
[...]int

2023-08-03 03:44 UTC, fumiama commented on plugin/bilibili/bilibilipush.go
> +	cache          sync.Map
请用syncx.Map

2023-08-03 03:44 UTC, fumiama commented on plugin/bilibili/bilibilipush.go
> +			str.WriteByte(orig[v])
记32个直接break就好了

2023-08-03 03:44 UTC, fumiama commented on plugin/bilibili/bilibilipush.go
> +func encWbi(params map[string]string, imgKey string, subKey string) map[string]string {
Wbi是啥，世界银行？

2023-08-03 03:44 UTC, fumiama commented on plugin/bilibili/bilibilipush.go
> +		keys = append(keys, k)
有没有一种可能，你可以
```go
keys := make([]string, len(params))
copy(keys, params)
```

2023-08-03 03:44 UTC, fumiama commented on plugin/bilibili/bilibilipush.go
> +		str.WriteString(fmt.Sprintf("%s=%s&", k, params[k]))
有必要sprintf吗，直接
```go
str.WriteString(k)
str.WriteByte('=')
str.WriteString(params[k])
str.WriteByte('&')
```

2023-08-03 03:44 UTC, fumiama commented on plugin/bilibili/bilibilipush.go
> +	hash := md5.Sum([]byte(query + mixinKey))
有没有一种可能，就是说你只要计算hash的话，完全没必要把query + mixinKey算出来，从上面那个strings.Builder开始，都可以
```go
h := md5.New()
h.Write(....)
hash := h.Sum(make([]byte, 0, md5.Size))
```

2023-08-03 03:44 UTC, fumiama commented on plugin/bilibili/bilibilipush.go
> +	lastUpdateTime = time.Now()
store都是sync.Map，这个变量你就不考虑并发了？

2023-08-03 03:44 UTC, fumiama commented on plugin/bilibili/bilibilipush.go
> +	updateCache()
展开放一个函数里不好吗？

2023-08-03 03:44 UTC, fumiama commented on plugin/bilibili/bilibilipush.go
> +	var err error
声明在这里有必要吗？

2023-08-03 03:44 UTC, fumiama commented on plugin/bilibili/bilibilipush.go
> +		cookie := ""
声明应该放这

2023-08-03 03:44 UTC, fumiama commented on plugin/bilibili/bilibilipush.go
> +	json := string(data)
binary.BytesToString()，莲宝就跟第一天写zbp一样

2023-08-03 03:44 UTC, fumiama commented on plugin/bilibili/bilibilipush.go
> +	imgKey := strings.Split(strings.Split(imgURL, "/")[len(strings.Split(imgURL, "/"))-1], ".")[0]
三个split套着，您认真的？快使用 strings.LastIndex() 和 strings.Cut()

2023-08-03 03:44 UTC, fumiama commented on plugin/bilibili/bilibilipush.go
> +		params[k] = v[0]
要判断一下len(v)

2023-08-03 03:44 UTC, fumiama commented on plugin/bilibili/bilibilipush.go
> +type XSpaceAccInfoRequest struct {
这玩意没用到吧？

2023-08-04 03:50 UTC, lianhong2758 commented on plugin/bilibili/bilibilipush.go
> +		keys = append(keys, k)
不可以,类型不同

2023-08-04 08:44 UTC, fumiama requested changes
好些了

2023-08-04 08:44 UTC, fumiama commented on plugin/bilibili/bilibilipush.go
> +func encWbi(params map[string]string, imgKey string, subKey string) map[string]string {
啊这，让你改的是Wbi这个名字本身不是加注释

2023-08-04 08:44 UTC, fumiama commented on plugin/bilibili/bilibilipush.go
> +		str.WriteString(k)
让你从sb就开始用md5的Write，不懂？

2023-08-04 08:44 UTC, fumiama commented on plugin/bilibili/bilibilipush.go
> +		return errors.New("未配置Bilbili-cookie")
你这啥大小写格式

2023-08-04 08:47 UTC, fumiama commented on plugin/bilibili/bilibilipush.go
> +		keys = append(keys, k)
那就从一开始就不要复制一份，直接range param不行吗

2023-08-23 04:25 UTC, fumiama approved these changes
莲宝真聪明

2023-08-23 04:25 UTC, merged