国际象棋
FloatTech/ZeroBot-Plugin pull request #720
Opened 2023-08-30 11:39 UTC by aimerneige

~~应该能跑吧~~，看下 lint

2023-08-30 12:02 UTC, aimerneige commented
![image](https://github.com/FloatTech/ZeroBot-Plugin/assets/51701792/78106ac5-47e1-4115-88d3-1628a1ff2e14)

测试了下，跑得妥妥的

2023-08-30 12:22 UTC, Jiang-Red commented on plugin/chess/assets/cheese.jpeg
这哪里用到了吗

2023-08-30 12:23 UTC, Jiang-Red commented on plugin/chess/assets/help.txt
直接硬编码即可

2023-08-30 12:25 UTC, Jiang-Red commented on plugin/chess/chess.go
> +	engine.OnRegex("[!|！]([0-9]|[A-Z]|[a-z]|=|-)+", zero.OnlyGroup).
没看懂这正则是用来做什么的，但也是错的，用`[!！]([0-9][A-Za-z][=\-])`，多在 https://regex101.com/ 在这个网站试试

2023-08-30 12:27 UTC, Jiang-Red commented on plugin/chess/chess.go
> +			userMsgStr := ctx.Event.Message.ExtractPlainText()
正则匹配到的内容都放在`ctx.State["regex_matched"].([]string)`里了，直接用就行，0是匹配的所有内容，1是第一个匹配组匹配的

2023-08-30 12:34 UTC, aimerneige commented on plugin/chess/chess.go
> +	engine.OnRegex("[!|！]([0-9]|[A-Z]|[a-z]|=|-)+", zero.OnlyGroup).
- 用来匹配 [代数记谱法](https://zh.wikipedia.org/zh-cn/%E4%BB%A3%E6%95%B8%E8%A8%98%E8%AD%9C%E6%B3%95)

- 这个正则的问题是会匹配到额外的内容，基本没啥问题，但是我不会改

- `[!！]([0-9][A-Za-z][=\-])` 不可用

2023-08-30 12:34 UTC, aimerneige commented on plugin/chess/assets/help.txt
改了

2023-08-30 12:50 UTC, Jiang-Red requested changes

2023-08-30 12:50 UTC, Jiang-Red commented on plugin/chess/chess.go
> +	})
在这里加一个`PrivateDataFolder`或者`PublicDataFolder`就会在data下自动创建文件夹了就不用下面的`tempFileDir`了

2023-08-30 12:50 UTC, Jiang-Red commented on plugin/chess/chess.go
> +			userName := ctx.Event.Sender.NickName
用`ctx.CardOrNickName()`可以获取群成员在群里的名字，如果没有再获取名片名字

2023-08-30 12:50 UTC, Jiang-Red commented on plugin/chess/core.go
> +func simpleText(msg string) message.Message {
不是很有必要的封装

2023-08-30 13:32 UTC, aimerneige commented on plugin/chess/core.go
> +			case chess.NoMethod:
lint 报错了

2023-08-30 13:35 UTC, aimerneige commented on plugin/chess/chess.go
> +			userName := ctx.Event.Sender.NickName
等级分排行榜不是各个群独立的，而是所有群共享，所以这里使用名牌名字更合适。

2023-08-30 13:55 UTC, aimerneige commented on plugin/chess/core.go
> +func simpleText(msg string) message.Message {
这是老框架迁移过来后带来的不合适的架构设计，主要的代码都是去年写的，而且断断续续加了不少功能，实在是懒得重构了，

2023-08-30 14:00 UTC, aimerneige commented on plugin/chess/core.go
> +			msg := "游戏结束，"
已优化

2023-08-30 14:00 UTC, aimerneige commented on plugin/chess/core.go
> +	ret := "当前等级分排行榜：\n\n"
已优化

2023-08-30 14:05 UTC, fumiama requested changes
总的来说感觉不错，比莲宝 @lianhong2758 好太多了，莲宝你多学学🤣👉

2023-08-30 14:05 UTC, fumiama commented on plugin/chess/core.go
> +		log.Errorln("[chess]", "Fail to get player ranking.", err)
无需向控制台输出错误。相反，应该将错误err的具体内容直接作为消息呈现给用户，这样才能在第一时间发现。下同。

2023-08-30 14:05 UTC, fumiama commented on plugin/chess/core.go
> +	svgFilePath := path.Join(tempFileDir, fmt.Sprintf("%d.svg", groupCode))
注意反并发

2023-08-30 14:05 UTC, fumiama commented on plugin/chess/core.go
> +	f, err := os.Create(svgFilePath)
注意反并发

2023-08-30 14:09 UTC, aimerneige commented on plugin/chess/chess.go
> +		err := os.MkdirAll(tempFileDir, 0750)
隔壁 `score` 抄过来的（

2023-08-30 14:16 UTC, aimerneige commented on plugin/chess/core.go
> +	_ "embed" // for embed assets
这个忘记了

2023-08-30 14:28 UTC, aimerneige commented on plugin/chess/chess.go
> +	engine.OnRegex("[!|！]([0-9]|[A-Z]|[a-z]|=|-)+", zero.OnlyGroup).
`^[!|！]([0-8]|[R|N|B|Q|K|O|a-h|x]|[-|=|+])+$` 就够用了，误匹配率很低的

2023-08-30 15:48 UTC, lianhong2758 commented
> 总的来说感觉不错，比莲宝 @lianhong2758 好太多了，莲宝你多学学🤣👉

你是?

2023-08-31 03:41 UTC, aimerneige commented on plugin/chess/chess.go
> +			userMsgStr = strings.Replace(userMsgStr, "！", "!", 1)
已优化

2023-08-31 05:39 UTC, aimerneige commented on plugin/chess/chess.go
> +			userName := ctx.Event.Sender.NickName
空字符串并不会造成错误，名片只用于排行榜

2023-08-31 05:50 UTC, aimerneige commented on plugin/chess/core.go
> +	// TODO: 使用原生 go 库渲染 svg
可以考虑使用等宽字体渲染图片

2023-08-31 06:20 UTC, aimerneige commented
剩下的不会改了
<img src="https://media3.giphy.com/media/3ov9jPBQ1UJRNS8MDe/giphy.gif" width="200"/>

2023-08-31 09:27 UTC, aimerneige commented on plugin/chess/core.go
> +	// TODO: 使用原生 go 库渲染 svg
已完成

2023-08-31 14:02 UTC, fumiama requested changes
最好还是不要用cmd.exec，我偏向于纯go实现。 @kanrichan 你那个能用吗？

2023-08-31 14:02 UTC, fumiama commented on plugin/chess/core.go
> +	f, err := os.Create(svgFilePath)
群反并发并非就万事大吉了，一样要做文件的反并发。简单的方法是只在程序启动时才清理/重建一次目录，然后就不管了。

2023-08-31 14:02 UTC, fumiama commented on plugin/chess/core.go
> +	if err := pos.UnmarshalText([]byte(fenStr)); err != nil {
binary.StringToBytes(fenStr)，其它地方如果也有这种用法则类推。还有binary.BytesToString()可使用。

2023-08-31 14:21 UTC, Jiang-Red commented on plugin/chess/core.go
> +	fnt := text.GNUUnifontFontFile
更新依赖用`go get github.com/FloatTech/zbputils@commit`
比如`go get github.com/FloatTech/zbputils@28c5ba5`

2023-09-01 09:20 UTC, aimerneige commented on plugin/chess/core.go
> +	svgFilePath := path.Join(tempFileDir, fmt.Sprintf("%d.svg", groupCode))
单个群内同时只允许同时存在一个对局，使用群号作为区分即可解决并发问题。

只有当用户发请求走棋时才需要读取图片，而棋盘也应该同步更新，实际操作为使用新的图片覆盖旧的图片，并立即读取，同一个群/即同一个对局中，图片读取完成后会立即失效，后续不再用到，使用新的图片覆盖也不会存在问题。不同的群/即不同的对局读写的文件路径是完全不同的，相互之间不会存在并发错误。

如果所有文件都使用随机值而不加有效区分的话，会生成大量的临时文件占用磁盘空间。每一次走棋会生成 `30KB` 的 svg 图片和 `80KB` 的 png 图片。一盘游戏平均要走 40 步，耗费 20 分钟，即约 4MB 的空间浪费。

2023-09-01 09:31 UTC, aimerneige commented on plugin/chess/core.go
> +	if err := pos.UnmarshalText([]byte(fenStr)); err != nil {
已修复，经查找只此处使用了如上写法

2023-09-01 09:32 UTC, aimerneige commented on plugin/chess/core.go
> +	boardString = strings.TrimPrefix(boardString, "\n")
已优化

2023-09-01 09:35 UTC, aimerneige commented on plugin/chess/core.go
> +func getBoardElement(groupCode int64) (*message.MessageSegment, bool, string) {
已优化

2023-09-01 09:36 UTC, aimerneige commented on plugin/chess/core.go
> +var chessRoomMap syncx.Map[int64, chessRoom]
已优化

2023-09-01 09:37 UTC, aimerneige commented on plugin/chess/chess.go
> +			userName := ctx.Event.Sender.NickName
已修复

2023-09-01 09:38 UTC, fumiama commented on plugin/chess/core.go
> +	svgFilePath := path.Join(tempFileDir, fmt.Sprintf("%d.svg", groupCode))
那可否不存这个图片，直接作为base64发送，svg渲染用 @kanrichan 的 https://github.com/kanrichan/resvg-go

2023-09-01 09:45 UTC, aimerneige commented on plugin/chess/core.go
> +	svgFilePath := path.Join(tempFileDir, fmt.Sprintf("%d.svg", groupCode))
我试着改一下

2023-09-01 10:15 UTC, aimerneige commented on plugin/chess/core.go
> +	fnt := text.GNUUnifontFontFile
已完成

2023-09-01 12:09 UTC, aimerneige commented on plugin/chess/core.go
> +	svgFilePath := path.Join(tempFileDir, fmt.Sprintf("%d.svg", groupCode))
> 可否不存这个图片

不可以，调用`inkscape`必须指定文件路径

> svg渲染用 @kanrichan 的 https://github.com/kanrichan/resvg-go

不会用

<img src="https://media1.giphy.com/media/1TGke2Ba9nbisAXQsJ/giphy.gif" height="200"/>

2023-09-01 12:17 UTC, aimerneige commented on plugin/chess/core.go
> +		log.Errorln("[chess]", "Fail to draw a game.", err)
已将日志格式改为 Debug 并添加了错误消息返回

2023-09-01 12:18 UTC, aimerneige commented on plugin/chess/core.go
> +		log.Errorln("[chess]", "Fail to get player ranking.", err)
已修复

2023-09-01 12:59 UTC, aimerneige commented
目前可行的解决方案：

1. 尝试使用 [kanrichan/resvg-go(]https://github.com/kanrichan/resvg-go) 渲染 svg 图
2. 删除 inkscape 相关代码，只使用等宽字体渲染的棋盘
3. 直接使用绘图库绘制棋盘，不使用 [notnil/chess](https://github.com/notnil/chess) 提供的 svg

2023-09-01 14:20 UTC, fumiama approved these changes

2023-09-01 14:20 UTC, fumiama commented on plugin/chess/core.go
> +		return abortGame(*room, groupCode, "对局已被管理员中断，游戏结束。")
你这函数，同步改成指针啊，算了我改吧。

2023-09-01 14:21 UTC, merged

2023-09-02 04:52 UTC, aimerneige commented
- [ ] 新改的代码还没运行测试