添加vtb语音包
FloatTech/ZeroBot-Plugin pull request #74
Opened 2021-11-07 11:41 UTC by guohuiyuan

2021-11-09 04:44 UTC, fumiama commented
建议替换`gorm`为[tinydb](https://github.com/Yiwen-Chan/tinydb)

2021-11-09 05:00 UTC, Yiwen-Chan commented
> 建议替换`gorm`为[tinydb](https://github.com/Yiwen-Chan/tinydb)

现在还不行，还没稳定下来

2021-11-09 05:01 UTC, Yiwen-Chan commented
可以先改一改 gorm 的 sqlite 的依赖，改成 modernc.org/sqlite

2021-11-19 14:34 UTC, fumiama commented on plugin_vtb_quotation/vtb_quotation.go
> +			db, err := gorm.Open("sqlite3", "data/VtbQuotation/vtb.db")
建议参考`plugin_diana/data/text.go`做一个自动下载数据库。

2021-11-19 15:00 UTC, guohuiyuan commented
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月19日(星期五) 晚上10:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FloatTech/ZeroBot-Plugin] 添加vtb语音包 (PR #74)





 
@fumiama commented on this pull request.
 
 
In plugin_vtb_quotation/vtb_quotation.go:
 &gt; +} +func init() { +	engine := control.Register("vtbquotation", &amp;control.Options{ +		DisableOnDefault: false, +		Help: "vtb语录\n" + +			"随机vtb\n", +	}) +	engine.OnFullMatch("vtb语录").SetBlock(true). +		Handle(func(ctx *zero.Ctx) { +			var firstIndex int +			var secondIndex int +			var thirdIndex int +			echo, cancel := ctx.FutureEvent("message", +				ctx.CheckSession()). // 只复读开启复读模式的人的消息 +				Repeat()             // 不断监听复读 +			db, err := gorm.Open("sqlite3", "data/VtbQuotation/vtb.db")  
建议参考plugin_diana/data/text.go做一个自动下载数据库。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-11-19 16:54 UTC, fumiama commented
`go.mod`有冲突，把`ZeroBot`更新到`v1.4.1`即可解决。

2021-11-19 16:56 UTC, guohuiyuan commented
改了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月20日(星期六) 凌晨0:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FloatTech/ZeroBot-Plugin] 添加vtb语音包 (PR #74)





 
go.mod有冲突，把ZeroBot更新到v1.4.1即可解决。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-11-19 17:00 UTC, fumiama requested changes

2021-11-19 17:00 UTC, fumiama commented on go.mod
> +	github.com/robfig/cron v1.2.0
不需要这个`cron`，我已经引入了，详见`manager`

2021-11-19 17:00 UTC, fumiama commented on go.mod
> +	github.com/logoove/sqlite v1.13.0
这个和`modernc.org/sqlite`重复

2021-11-19 17:00 UTC, fumiama commented on plugin_vtb_quotation/cron/cron.go
> +func VtbData() {
建议用`private`

2021-11-19 17:00 UTC, fumiama commented on plugin_vtb_quotation/model/model.go
> +	Path := "data/VtbQuotation/vtb.db"
建议用`path`，其他同理

2021-11-19 17:00 UTC, fumiama commented on plugin_vtb_quotation/utils/utils.go
> +	agent := [...]string{
建议用全局变量

2021-11-19 17:04 UTC, guohuiyuan commented
modernc.org/sqlite不能完全替换gorm的sqlite驱动，名称不一样，建议把项目的modernc.org改成github.com/logoove/sqlite



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月20日(星期六) 凌晨1:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FloatTech/ZeroBot-Plugin] 添加vtb语音包 (PR #74)





 
@fumiama requested changes on this pull request.
 
 
In go.mod:
 &gt;  	github.com/mroth/weightedrand v0.4.1 +	github.com/robfig/cron v1.2.0  
不需要这个cron，我已经引入了，详见manager
 
 
In go.mod:
 &gt; @@ -13,11 +13,14 @@ require (  	github.com/gin-gonic/gin v1.7.4  	github.com/golang/protobuf v1.5.2  	github.com/gorilla/websocket v1.4.2 +	github.com/jinzhu/gorm v1.9.16 +	github.com/logoove/sqlite v1.13.0  
这个和modernc.org/sqlite重复
 
 
In plugin_vtb_quotation/cron/cron.go:
 &gt; +	"github.com/FloatTech/ZeroBot-Plugin/plugin_vtb_quotation/secondVtb" +	"github.com/robfig/cron" +	log "github.com/sirupsen/logrus" +) + +func VtbDaily() { +	log.Println("创建vtb数据库定时任务") +	c := cron.New() +	if err := c.AddFunc("0 0 4 * * ?", func() { VtbData() }); err != nil { +		log.Println("定时任务有错误:", err) +	} else { +		log.Println("开启vtb数据库定时任务") +		c.Start() +	} +} +func VtbData() {  
建议用private
 
 
In plugin_vtb_quotation/model/model.go:
 &gt; +	_ "github.com/logoove/sqlite" +	log "github.com/sirupsen/logrus" + +	"math/rand" +	"os" +	"strconv" +	"time" +) + +var ( +	Db *gorm.DB +) + +func Init() { +	var err error +	Path := "data/VtbQuotation/vtb.db"  
建议用path，其他同理
 
 
In plugin_vtb_quotation/utils/utils.go:
 &gt; @@ -0,0 +1,24 @@ +package utils + +import ( +	"math/rand" +	"time" +) + +func GetAgent() string { +	agent := [...]string{  
建议用全局变量
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-11-19 17:17 UTC, guohuiyuan commented
你那个定时错误方法为什么只有5个参数






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月20日(星期六) 凌晨1:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FloatTech/ZeroBot-Plugin] 添加vtb语音包 (PR #74)





 
@fumiama requested changes on this pull request.
 
 
In go.mod:
 &gt;  	github.com/mroth/weightedrand v0.4.1 +	github.com/robfig/cron v1.2.0  
不需要这个cron，我已经引入了，详见manager
 
 
In go.mod:
 &gt; @@ -13,11 +13,14 @@ require (  	github.com/gin-gonic/gin v1.7.4  	github.com/golang/protobuf v1.5.2  	github.com/gorilla/websocket v1.4.2 +	github.com/jinzhu/gorm v1.9.16 +	github.com/logoove/sqlite v1.13.0  
这个和modernc.org/sqlite重复
 
 
In plugin_vtb_quotation/cron/cron.go:
 &gt; +	"github.com/FloatTech/ZeroBot-Plugin/plugin_vtb_quotation/secondVtb" +	"github.com/robfig/cron" +	log "github.com/sirupsen/logrus" +) + +func VtbDaily() { +	log.Println("创建vtb数据库定时任务") +	c := cron.New() +	if err := c.AddFunc("0 0 4 * * ?", func() { VtbData() }); err != nil { +		log.Println("定时任务有错误:", err) +	} else { +		log.Println("开启vtb数据库定时任务") +		c.Start() +	} +} +func VtbData() {  
建议用private
 
 
In plugin_vtb_quotation/model/model.go:
 &gt; +	_ "github.com/logoove/sqlite" +	log "github.com/sirupsen/logrus" + +	"math/rand" +	"os" +	"strconv" +	"time" +) + +var ( +	Db *gorm.DB +) + +func Init() { +	var err error +	Path := "data/VtbQuotation/vtb.db"  
建议用path，其他同理
 
 
In plugin_vtb_quotation/utils/utils.go:
 &gt; @@ -0,0 +1,24 @@ +package utils + +import ( +	"math/rand" +	"time" +) + +func GetAgent() string { +	agent := [...]string{  
建议用全局变量
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-11-19 17:19 UTC, guohuiyuan commented
你有确认过bilibili包里面的定时任务能正确执行吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月20日(星期六) 凌晨1:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FloatTech/ZeroBot-Plugin] 添加vtb语音包 (PR #74)





 
@fumiama requested changes on this pull request.
 
 
In go.mod:
 &gt;  	github.com/mroth/weightedrand v0.4.1 +	github.com/robfig/cron v1.2.0  
不需要这个cron，我已经引入了，详见manager
 
 
In go.mod:
 &gt; @@ -13,11 +13,14 @@ require (  	github.com/gin-gonic/gin v1.7.4  	github.com/golang/protobuf v1.5.2  	github.com/gorilla/websocket v1.4.2 +	github.com/jinzhu/gorm v1.9.16 +	github.com/logoove/sqlite v1.13.0  
这个和modernc.org/sqlite重复
 
 
In plugin_vtb_quotation/cron/cron.go:
 &gt; +	"github.com/FloatTech/ZeroBot-Plugin/plugin_vtb_quotation/secondVtb" +	"github.com/robfig/cron" +	log "github.com/sirupsen/logrus" +) + +func VtbDaily() { +	log.Println("创建vtb数据库定时任务") +	c := cron.New() +	if err := c.AddFunc("0 0 4 * * ?", func() { VtbData() }); err != nil { +		log.Println("定时任务有错误:", err) +	} else { +		log.Println("开启vtb数据库定时任务") +		c.Start() +	} +} +func VtbData() {  
建议用private
 
 
In plugin_vtb_quotation/model/model.go:
 &gt; +	_ "github.com/logoove/sqlite" +	log "github.com/sirupsen/logrus" + +	"math/rand" +	"os" +	"strconv" +	"time" +) + +var ( +	Db *gorm.DB +) + +func Init() { +	var err error +	Path := "data/VtbQuotation/vtb.db"  
建议用path，其他同理
 
 
In plugin_vtb_quotation/utils/utils.go:
 &gt; @@ -0,0 +1,24 @@ +package utils + +import ( +	"math/rand" +	"time" +) + +func GetAgent() string { +	agent := [...]string{  
建议用全局变量
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-11-20 03:21 UTC, fumiama commented
> modernc.org/sqlite不能完全替换gorm的sqlite驱动，名称不一样，建议把项目的modernc.org改成github.com/logoove/sqlite

可以，近期替换

2021-11-20 03:24 UTC, fumiama commented
> 你有确认过bilibili包里面的定时任务能正确执行吗

没有，不过这个仓库的来源就是`bilibili`那个的`cron`，基本上没有大修改。

2021-11-20 03:26 UTC, fumiama commented
> 你那个定时任务方法为什么只有5个参数

参见 https://pkg.go.dev/github.com/fumiama/cron

![屏幕快照 2021-11-20 上午11 25 56](https://user-images.githubusercontent.com/41315874/142712966-f8d3fce8-10cd-4ea3-9091-8f4bc3486fcb.png)

2021-11-20 03:28 UTC, fumiama commented
还有`go.sum`的冲突没有解决，可以直接回退`go.sum`到不冲突的版本。

2021-11-20 03:31 UTC, fumiama commented on plugin_vtb_quotation/model/model.go
> +	Path = "data/VtbQuotation/vtb.db"
这里也没有必要用大写

2021-11-20 03:37 UTC, guohuiyuan commented
// 定时任务每天晚上最后2分钟执行一次
func fansDaily(groupID int64) {
   c := cron.New()
   _, err := c.AddFunc("0 58 23 * * ?", func() { fansData(groupID) })
   if err == nil {
      c.Start()
   }
}bilibili那个包定时任务写错了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月20日(星期六) 中午11:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FloatTech/ZeroBot-Plugin] 添加vtb语音包 (PR #74)





  
你有确认过bilibili包里面的定时任务能正确执行吗
  
没有，不过这个仓库的来源就是bilibili那个的cron，基本上没有大修改。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-11-20 03:40 UTC, fumiama commented
> bilibili那个包定时任务写错了

哦，不过`cron`本身是能用的，`manager`我测试过。

2021-11-20 05:04 UTC, fumiama commented
你看看还改不改，不改我就合并

2021-11-20 05:05 UTC, fumiama approved these changes

2021-11-20 05:34 UTC, merged