add control for saucenao & bilibili_parse
FloatTech/ZeroBot-Plugin pull request #839
Opened 2023-12-29 23:51 UTC by shudorcl

观察到以图搜图可能会发出NSFW图片，以及B站视频总结很多时候占据太多版面，于是为其增加了控制指令

不过GetData/SetData没看太明白，至少运行起来是有效的）

2024-01-02 14:38 UTC, Jiang-Red commented
看到这个pr才意识到每个用到getdata的插件都没有对取到的状态进行缓存

2024-01-07 06:48 UTC, fumiama commented
过一阵仔细看看。

2024-05-04 09:06 UTC, fumiama requested changes

2024-05-04 09:06 UTC, fumiama commented on plugin/bilibili/bilibili_parse.go
> +	en.OnRegex(`^(.*)视频总结$`, zero.AdminPermission).SetBlock(true).
`^(开启|打开....)视频总结$`

2024-05-04 09:06 UTC, fumiama commented on plugin/bilibili/bilibili_parse.go
> +			if ok {
```go
if !ok {
    ctx.SendChain(message.Text("找不到服务!"))
    return
}
```

2024-05-04 09:06 UTC, fumiama commented on plugin/bilibili/bilibili_parse.go
> +					data |= 0x10
可将`0x10`定义为一个`const`放在最上面，以便日后统一维护。

2024-05-04 09:06 UTC, fumiama commented on plugin/saucenao/searcher.go
> +			if ok && c.GetData(ctx.Event.GroupID)&0x10 == 0x10 {
同，定义const

2024-05-04 09:06 UTC, fumiama commented on plugin/saucenao/searcher.go
> +							message.Text(fmt.Sprintf(
`message.Text`部分都是一样的，应该提出if。

2024-05-04 09:06 UTC, fumiama commented on plugin/saucenao/searcher.go
> +			if ok {
if !ok ...

2024-05-04 09:06 UTC, fumiama commented on plugin/saucenao/searcher.go
> +	engine.OnRegex(`^(.*)搜图显示图片$`, zero.AdminPermission).SetBlock(true).
(开启|打开|...)

2024-05-04 16:04 UTC, fumiama approved these changes

2024-05-04 16:07 UTC, merged