新增统计睡眠时间和添加协程里的异常捕获
FloatTech/ZeroBot-Plugin pull request #84
Opened 2021-12-03 09:26 UTC by guohuiyuan

2021-12-03 10:52 UTC, fumiama requested changes

2021-12-03 10:52 UTC, fumiama commented on main.go
> +	_ "github.com/FloatTech/ZeroBot-Plugin/plugin_sleep_manage" //统计睡眠时间
注释要空一格，其他地方同理

2021-12-03 10:52 UTC, fumiama commented on plugin_sleep_manage/sleep_manage.go
> +				ctx.SendChain(message.Reply(ctx.Event.MessageID), message.Text(fmt.Sprintf("早安成功！你是今天第%d个起床的", position)))
“早安成功”作为问候可能略显奇怪，建议改成更加人性化的表述。

2021-12-03 10:52 UTC, fumiama commented on plugin_sleep_manage/sleep_manage.go
> +func timeChange(time time.Duration) (hour, minute, second int64) {
函数名应为Duration而非Change

2021-12-03 10:52 UTC, fumiama commented on plugin_sleep_manage/model/model.go
> +	SleepTime time.Time `gorm:"column:sleep_time"`
事实上睡眠时间和起床时间不可能同时被用到，因此可以简化为一个时间。

2021-12-03 10:52 UTC, fumiama commented on plugin_sleep_manage/sleep_manage.go
> +	engine.OnFullMatch("早安", isMorning).SetBlock(true).SetPriority(prio).
需要添加`zero.OnlyGroup`的`Rule`，晚安同理。

2021-12-04 03:41 UTC, fumiama requested changes

2021-12-04 03:41 UTC, fumiama commented on main.go
> +	zero.OnFullMatchGroup([]string{"/help", ".help", "help", "帮助", "菜单"}, zero.OnlyToMe).SetBlock(true).FirstPriority().
不要添加"help", "帮助"，会和青云客的帮助冲突

2021-12-04 03:41 UTC, fumiama commented on main.go
> +			ctx.SendChain(message.Text(control.TotalHelp(ctx.Event.GroupID)))
直接打印全部列表会显得过于冗长，建议只是提示"发送 /服务列表 以查看所有服务"，不要这个`TotalHelp`了

2021-12-04 03:41 UTC, fumiama commented on control/rule.go
> +func TotalHelp(gid int64) (msg string) {
理由见下方，建议还原更改。

2021-12-04 03:41 UTC, fumiama commented on plugin_manager/manager.go
> +	"github.com/FloatTech/ZeroBot-Plugin/control"
这个需要移动到`import`最下方，与其他包空一行

2021-12-04 03:41 UTC, fumiama commented on plugin_manager/manager.go
> +	engine.OnFullMatch("群管系统", zero.AdminPermission).SetBlock(true).FirstPriority().
既然有了help，群管系统这个命令就不再需要了，可以移除

2021-12-04 03:41 UTC, fumiama commented on plugin_manager/manager.go
> +	engine.OnRegex(`^退出群聊.*?(\d+)`, zero.OnlyGroup, zero.SuperUserPermission).SetBlock(true).SetPriority(40).
这里可以把`zero.OnlyGroup`也改成`zero.OnlyToMe`

2021-12-04 03:47 UTC, guohuiyuan commented
主要是我想让用户更加简单的触发help，那个打印的是服务列表+用法的全部信息，有很多功能不知道，要知道用法需要两步有点难搞



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月4日(星期六) 中午11:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FloatTech/ZeroBot-Plugin] 新增统计睡眠时间和添加协程里的异常捕获 (PR #84)





 
@fumiama requested changes on this pull request.
 
 
In main.go:
 &gt; @@ -118,8 +120,9 @@ func printBanner() {  func main() {  	printBanner()  	// 帮助 -	zero.OnFullMatchGroup([]string{"/help", ".help", "菜单"}, zero.OnlyToMe).SetBlock(true).FirstPriority(). +	zero.OnFullMatchGroup([]string{"/help", ".help", "help", "帮助", "菜单"}, zero.OnlyToMe).SetBlock(true).FirstPriority().  
不要添加"help", "帮助"，会和青云客的帮助冲突
 
 
In main.go:
 &gt;  		Handle(func(ctx *zero.Ctx) { +			ctx.SendChain(message.Text(control.TotalHelp(ctx.Event.GroupID)))  
直接打印全部列表会显得过于冗长，建议只是提示"发送 /服务列表 以查看所有服务"，不要这个TotalHelp了
 
 
In control/rule.go:
 &gt; @@ -215,6 +215,25 @@ func copyMap(m map[string]*Control) map[string]*Control {  	return ret  }   +func TotalHelp(gid int64) (msg string) {  
理由见下方，建议还原更改。
 
 
In plugin_manager/manager.go:
 &gt; @@ -3,6 +3,7 @@ package manager    import (  	"fmt" +	"github.com/FloatTech/ZeroBot-Plugin/control"  
这个需要移动到import最下方，与其他包空一行
 
 
In plugin_manager/manager.go:
 &gt; @@ -66,12 +71,12 @@ func init() { // 插件主体  		clock = timer.NewClock(timerfile)  	}()  	// 菜单 -	zero.OnFullMatch("群管系统", zero.AdminPermission).SetBlock(true).FirstPriority(). +	engine.OnFullMatch("群管系统", zero.AdminPermission).SetBlock(true).FirstPriority().  
既然有了help，群管系统这个命令就不再需要了，可以移除
 
 
In plugin_manager/manager.go:
 &gt; @@ -116,15 +121,15 @@ func init() { // 插件主体  			ctx.SendChain(message.Text("残念~ " + nickname + " 被放逐"))  		})  	// 退出群聊 -	zero.OnRegex(`^退出群聊.*?(\d+)`, zero.OnlyGroup, zero.AdminPermission).SetBlock(true).SetPriority(40). +	engine.OnRegex(`^退出群聊.*?(\d+)`, zero.OnlyGroup, zero.SuperUserPermission).SetBlock(true).SetPriority(40).  
这里可以把zero.OnlyGroup也改成zero.OnlyToMe
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-12-04 03:50 UTC, guohuiyuan commented on main.go
> +			ctx.SendChain(message.Text(control.TotalHelp(ctx.Event.GroupID)))
等下我会改成合并消息，初衷是为了更快速的知道，所有操作的用法

2021-12-04 03:51 UTC, fumiama commented
> 主要是我想让用户更加简单的触发help，那个打印的是服务列表+用法的全部信息，有很多功能不知道，要知道用法需要两步有点难搞

但是实在太长了...

2021-12-04 03:51 UTC, guohuiyuan commented on plugin_sleep_manage/sleep_manage.go
> +				ctx.SendChain(message.Reply(ctx.Event.MessageID), message.Text(fmt.Sprintf("早安成功！你是今天第%d个起床的", position)))
我觉得早安成功好像还行😂

2021-12-04 03:52 UTC, guohuiyuan commented
我会改成合并消息




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月4日(星期六) 中午11:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FloatTech/ZeroBot-Plugin] 新增统计睡眠时间和添加协程里的异常捕获 (PR #84)





  
主要是我想让用户更加简单的触发help，那个打印的是服务列表+用法的全部信息，有很多功能不知道，要知道用法需要两步有点难搞
  
但是实在太长了...
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-12-04 03:55 UTC, fumiama commented
> 我会改成合并消息

可以，不过建议另外用别的关键词触发，help还是保持简洁，仅提示这个触发关键词，以及 /服务列表 + /用法 的两级查询结构。

2021-12-04 03:56 UTC, fumiama commented on plugin_sleep_manage/sleep_manage.go
> +				ctx.SendChain(message.Reply(ctx.Event.MessageID), message.Text(fmt.Sprintf("早安成功！你是今天第%d个起床的", position)))
嘛。。。好吧

2021-12-04 03:57 UTC, fumiama commented on main.go
> +			ctx.SendChain(message.Text(control.TotalHelp(ctx.Event.GroupID)))
可以另取关键词，直接放到control

2021-12-04 03:57 UTC, fumiama commented on control/rule.go
> +func TotalHelp(gid int64) (msg string) {
直接在control触发的话，这个函数就不需要了

2021-12-04 12:43 UTC, fumiama approved these changes
没有其他更改我就合并了

2021-12-04 12:44 UTC, guohuiyuan commented
没有了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月4日(星期六) 晚上8:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FloatTech/ZeroBot-Plugin] 新增统计睡眠时间和添加协程里的异常捕获 (PR #84)





 
@fumiama approved this pull request.
 
没有其他更改我就合并了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-12-04 12:46 UTC, merged