fix:修复sql错误
FloatTech/ZeroBot-Plugin pull request #85
Opened 2021-12-05 04:45 UTC by guohuiyuan

2021-12-06 10:57 UTC, fumiama requested changes

2021-12-06 10:57 UTC, fumiama commented on plugin_book_review/book_review.go
> +	//blank = `\n`
注释空格

2021-12-06 10:57 UTC, fumiama commented on plugin_book_review/book_review.go
> +			defer db.Close()
单返回无需defer，在最后close即可，其余defer同理

2021-12-06 10:57 UTC, fumiama commented on plugin_book_review/book_review.go
> +			// 合并消息屡次出错暂时不用
建议调试好后再发新pr，错误代码不要在注释中给出，以免对其他人产生误导。

2021-12-06 10:57 UTC, fumiama commented on plugin_book_review/data.go
> +	"github.com/FloatTech/ZeroBot-Plugin/utils/file"
格式问题，看看其他代码是如何排列import的

2021-12-06 10:57 UTC, fumiama commented on plugin_book_review/model/model.go
> +	BookReview string `gorm:"column:book_review"`
这种简单的数据库建议直接用`utils/sql`，自带随机选取函数`Pick`

2021-12-07 10:38 UTC, fumiama approved these changes
ok，sql那个可以我来改，你看看还有什么要改的

2021-12-07 15:50 UTC, guohuiyuan commented
没有了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月7日(星期二) 晚上6:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FloatTech/ZeroBot-Plugin] fix:修复sql错误 (PR #85)





 
@fumiama approved this pull request.
 
ok，sql那个可以我来改，你看看还有什么要改的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-12-08 05:12 UTC, merged

2021-12-08 09:51 UTC, fumiama commented
我改了sql，你注意同步一下，不要在老的上改了

2021-12-08 12:42 UTC, guohuiyuan commented
ok



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月8日(星期三) 下午5:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FloatTech/ZeroBot-Plugin] fix:修复sql错误 (PR #85)





 
我改了sql，你注意同步一下，不要在老的上改了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.