update guessmusic:Reduce the difficulty
FloatTech/ZeroBot-Plugin pull request #854
Opened 2024-01-19 15:27 UTC by vatebur

猜歌时忽略大小写和简繁体，降低猜歌难度
Neglecting capitalization and simplified traditional Chinese when guessing music reduces the difficulty of guessing music

2024-01-19 15:29 UTC, vatebur commented
`guessmusic` 用的独角兽API已经失效了，是否能把相关部分直接删除。

2024-01-20 06:22 UTC, fumiama requested changes

2024-01-20 06:22 UTC, fumiama commented on plugin/guessmusic/guessmusic.go
> +	t2s, err := gocc.New("t2s")
不应当每次计算都New，而是将它作为全局变量。

2024-01-23 09:30 UTC, vatebur commented
API已经跑路了

2024-01-25 08:39 UTC, fumiama commented
先合了，等找到新的再看看怎么改改吧😂

2024-01-25 08:40 UTC, fumiama approved these changes

2024-01-25 08:40 UTC, merged