✨ 添加两个api接口
FloatTech/ZeroBot-Plugin pull request #886
Opened 2024-04-10 14:30 UTC by guohuiyuan

2024-04-10 16:02 UTC, guohuiyuan commented on plugin/lolimi/lolimi.go
> +		switch name {
你仔细看，返回的格式有不一样的

2024-04-10 17:06 UTC, fumiama commented on plugin/lolimi/lolimi.go
> +		switch name {
至少可以分两组吧，比如前面获取data一次，后面看加不加music。

2024-04-10 17:07 UTC, fumiama requested changes

2024-04-10 17:07 UTC, fumiama commented on plugin/yujn/yujn.go
> +		switch videoType {
使用map而非switch，map放全局变量。

2024-04-12 14:10 UTC, fumiama requested changes

2024-04-12 14:10 UTC, fumiama commented on plugin/yujn/yujn.go
> +		videoURL := urlMap[videoType]
ok或""回落到fallback

2024-04-13 08:00 UTC, guohuiyuan commented on plugin/yujn/yujn.go
> +		videoURL := urlMap[videoType]
没有理解什么意思。。把“”删掉算了，不可能空

2024-04-13 08:51 UTC, fumiama approved these changes

2024-04-13 08:51 UTC, fumiama commented on plugin/yujn/yujn.go
> +		videoURL := urlMap[videoType]
也行吧

2024-04-13 08:51 UTC, merged