add robbery plugin
FloatTech/ZeroBot-Plugin pull request #893
Opened 2024-04-29 06:54 UTC by vatebur

https://github.com/FloatTech/ZeroBot-Plugin/issues/2#issuecomment-1681474703

add robbery plugin
添加打劫插件，打劫群友的Atri币

- 打劫[对方Q号|@对方QQ]
1. 受害者钱包少于1000不能被打劫
2. 打劫成功率 40%
4. 打劫失败罚款1000（钱不够不罚钱）
5. 保险赔付0-80%
6. 打劫成功获得对方0-5%+500的财产（最高1W）
7. 每日可打劫或被打劫一次
8. 打劫失败不计入次数

2024-04-30 11:56 UTC, fumiama approved these changes

2024-04-30 11:56 UTC, fumiama requested changes
还需要在README相应位置添加说明，记得遵守main.go的排序。

2024-05-06 01:49 UTC, vatebur commented
## change log
1. 使用rebase追平主分支的提交
2. 在README.md 里添加对应的功能说明
3. 应用 lint 的建议，修改import顺序

2024-05-06 10:44 UTC, fumiama approved these changes

2024-05-06 10:44 UTC, merged