[mcfish]  Add one click selling
FloatTech/ZeroBot-Plugin pull request #894
Opened 2024-04-29 09:24 UTC by vatebur

Add one click waste selling function to mcfish plugin
给mcfish 添加一键售卖垃圾功能

- 出售所有垃圾

2024-04-30 11:53 UTC, fumiama requested changes

2024-04-30 11:53 UTC, fumiama commented on plugin/mcfish/main.go
> +	count, err := sql.db.Count(name)
不必设这么多道检查，直接sql.db.FindFor就行了，没找到自然返回的是nil

2024-04-30 11:53 UTC, fumiama commented on plugin/mcfish/store.go
> +			ctx.SendChain(message.Text("[ERROR at store.go.5]:", err))
ERROR at 位置不对啊，建议不要写行号，毕竟不稳定。

2024-05-06 03:11 UTC, vatebur commented
## change log
1. 使用rebase追平主分支
2. 修改README.md里对应的功能说明
3. 感觉建议去掉了一部分错误检测和报错信息（代码写的少，没啥把握

2024-05-06 10:42 UTC, fumiama commented
Rebase不利于我查看diff，但是之前的问题其实不大，所以我直接合了。

2024-05-06 10:43 UTC, fumiama approved these changes

2024-05-06 10:43 UTC, merged