抽扑克！
FloatTech/ZeroBot-Plugin pull request #903
Opened 2024-05-10 15:19 UTC by aimerneige

2024-05-10 16:33 UTC, fumiama requested changes

2024-05-10 16:33 UTC, fumiama commented on plugin/poker/poker.go
> +	entries, _ := os.ReadDir(engine.DataFolder())
应当硬编码所有文件名，因为懒加载不会确保在未GetLazyData之前文件存在于该目录。

2024-05-10 16:33 UTC, fumiama commented on plugin/poker/poker.go
> +	imgData, err := os.ReadFile(randomImgPath)
使用GetLazyData，参考其他插件。

2024-05-11 17:21 UTC, aimerneige commented
updated @fumiama

2024-05-12 15:27 UTC, fumiama requested changes
README中加入相關條目

2024-05-12 15:36 UTC, aimerneige commented
> README中加入相關條目

solved

2024-05-12 15:36 UTC, fumiama approved these changes

2024-05-12 15:37 UTC, merged