✨ 添加水群时长统计
FloatTech/ZeroBot-Plugin pull request #913
Opened 2024-05-21 15:50 UTC by guohuiyuan

2024-05-25 06:39 UTC, fumiama requested changes

2024-05-25 06:39 UTC, fumiama commented on plugin/chatcount/chatcount.go
> +	engine.OnPrefix(`查询水群`, zero.OnlyGroup).SetBlock(true).Handle(func(ctx *zero.Ctx) {
有必要prefix吗

2024-05-25 06:39 UTC, fumiama commented on plugin/chatcount/model.go
> +	chatmu sync.Mutex
mu放struct里
```go
type chattimedb struct {
    sync.Mutex
    gorm.DB
}
```

2024-05-25 06:39 UTC, fumiama commented on plugin/chatcount/model.go
> +type ChatTime struct {
没必要大写

2024-05-25 06:39 UTC, fumiama commented on plugin/chatcount/chatcount.go
> +			todayTime, remindFlag := ctdb.updateChatTime(ctx.Event.GroupID, ctx.Event.UserID)
每一条消息都读一次数据库是不是开销太大了，建议加一层缓存。

2024-05-25 06:39 UTC, fumiama commented on plugin/chatcount/model.go
> +	if err := db.Model(&ChatTime{}).Where("group_id = ? and user_id = ?", gid, uid).First(&st).Error; err != nil {
怎么又if else套娃了，if return的范式忘了吗，这让我咋看，都是一坨

<img width="857" alt="截屏2024-05-25 下午3 38 10" src="https://github.com/FloatTech/ZeroBot-Plugin/assets/41315874/c63944c6-07d5-4a2f-9ca4-8dcbdfc60b8e">

2024-05-25 06:39 UTC, fumiama commented on plugin/chatcount/model.go
> +	db.Model(&ChatTime{}).Where("group_id = ? and user_id = ?", gid, uid).First(&st)
&ChatTime{}其实可以直接&st，其他地方同理。

2024-05-25 06:39 UTC, fumiama commented on plugin/chatcount/model.go
> +func getLevel(t int) int {
做一个type，把这个包装成level()方法。

2024-05-27 10:47 UTC, guohuiyuan commented on plugin/chatcount/chatcount.go
> +	engine.OnPrefix(`查询水群`, zero.OnlyGroup).SetBlock(true).Handle(func(ctx *zero.Ctx) {
![image](https://github.com/FloatTech/ZeroBot-Plugin/assets/54976075/147d08df-27dc-4933-b8cf-41fac3332ff2)
name := ctx.NickName() 这个干了很多事的
![image](https://github.com/FloatTech/ZeroBot-Plugin/assets/54976075/32186fc4-9a2b-498c-9ca1-680af458daf5)
很多都这样的

2024-05-27 10:48 UTC, guohuiyuan commented on plugin/chatcount/chatcount.go
> +			todayTime, remindFlag := ctdb.updateChatTime(ctx.Event.GroupID, ctx.Event.UserID)
这个不是读数据库，这个是更新数据库，要不直接不用数据库，改成内存

2024-05-27 10:49 UTC, guohuiyuan commented on plugin/chatcount/model.go
> +	if err := db.Model(&ChatTime{}).Where("group_id = ? and user_id = ?", gid, uid).First(&st).Error; err != nil {
![image](https://github.com/FloatTech/ZeroBot-Plugin/assets/54976075/625f5b22-7eba-424e-8177-45cf0fb1984c)
bu'hui不会有人审代码不用电脑吧

2024-05-28 12:04 UTC, fumiama commented on plugin/chatcount/chatcount.go
> +	engine.OnPrefix(`查询水群`, zero.OnlyGroup).SetBlock(true).Handle(func(ctx *zero.Ctx) {
okok，太hacking了

2024-05-28 12:04 UTC, fumiama commented on plugin/chatcount/chatcount.go
> +			todayTime, remindFlag := ctdb.updateChatTime(ctx.Event.GroupID, ctx.Event.UserID)
那你咋统计

2024-05-28 12:05 UTC, fumiama commented on plugin/chatcount/model.go
> +	if err := db.Model(&ChatTime{}).Where("group_id = ? and user_id = ?", gid, uid).First(&st).Error; err != nil {
谁给你下下来看，我直接网页打开的。

2024-05-29 07:59 UTC, guohuiyuan commented
大部分更新数据库，就算加查找缓存，还是要更新数据库的时间的，所以我打算把时间戳和时长都放在内存算了



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------
发件人: 源文雨 ***@***.***&gt;
发送时间: 2024年5月28日 20:05
收件人: FloatTech/ZeroBot-Plugin ***@***.***&gt;
抄送: himawari ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [FloatTech/ZeroBot-Plugin] ✨ 添加水群时长统计 (PR #913)





 
@fumiama commented on this pull request.
 
 
In plugin/chatcount/chatcount.go:
 &gt; +	rankSize = 15 +) + +func init() { +	engine := control.AutoRegister(&amp;ctrl.Options[*zero.Ctx]{ +		DisableOnDefault:  false, +		Brief:             "聊天时长统计", +		Help:              "- ***@***.***\n- 查看水群排名", +		PrivateDataFolder: "chatcount", +	}) +	go func() { +		ctdb = initialize(engine.DataFolder() + "chatcount.db") +	}() +	engine.OnMessage(zero.OnlyGroup).SetBlock(false). +		Handle(func(ctx *zero.Ctx) { +			todayTime, remindFlag := ctdb.updateChatTime(ctx.Event.GroupID, ctx.Event.UserID)  
那你咋统计
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2024-05-30 06:43 UTC, fumiama commented
> 大部分更新数据库，就算加查找缓存，还是要更新数据库的时间的，所以我打算把时间戳和时长都放在内存算了

也可以，毕竟是以天为基准，也不会重启那么频繁，每条消息写一次开销太大了。

2024-06-06 06:20 UTC, fumiama requested changes

2024-06-06 06:20 UTC, fumiama commented on plugin/chatcount/chatcount.go
> +		ctdb = initialize(engine.DataFolder() + "chatcount.db")
万一没init好就用了咋办

2024-06-06 06:20 UTC, fumiama commented on plugin/chatcount/model.go
> +func NewLeveler(levels []int) *Leveler {
无需大写。另外签名可优化为
```go
func NewLeveler(levels ...int) *Leveler
```

2024-06-06 06:20 UTC, fumiama commented on plugin/chatcount/model.go
> +type Leveler struct {
就一个字段，建议
```go
type leveler []int
```

2024-06-06 06:20 UTC, fumiama commented on plugin/chatcount/model.go
> +type ByTotalTimeDescMessageDesc []chatTime
名字太长了，另，无需大写。

2024-06-06 06:20 UTC, fumiama commented on plugin/chatcount/model.go
> +func (l *Leveler) Level(t int) int {
无需大写。

2024-06-07 14:10 UTC, guohuiyuan commented on plugin/chatcount/chatcount.go
> +		ctdb = initialize(engine.DataFolder() + "chatcount.db")
只要在第二天更新的时候才会用数据库

2024-06-07 14:26 UTC, guohuiyuan commented on plugin/chatcount/model.go
> +type Leveler struct {
那后面怎么实现方法

2024-06-07 14:27 UTC, guohuiyuan commented on plugin/chatcount/model.go
> +type Leveler struct {
不用结构体的话

2024-06-11 12:53 UTC, fumiama approved these changes

2024-06-11 12:53 UTC, merged

2024-06-11 12:53 UTC, fumiama commented on plugin/chatcount/model.go
> +type Leveler struct {
就像结构体一样写。