fix robbery bug：Wallet is negative
FloatTech/ZeroBot-Plugin pull request #914
Opened 2024-05-22 07:02 UTC by vatebur

fix robbery bug：Wallet is negative。
修复了打劫失败可能导致钱包为负数的情况。

先把插件给修了，API的修改好像有争议，不太敢动（技术菜），先观望一下。

2024-05-22 07:29 UTC, vatebur commented
特别鸣谢一下群友@星尘/空之梦

2024-05-25 06:29 UTC, fumiama approved these changes

2024-05-25 06:29 UTC, fumiama requested changes

2024-05-25 06:29 UTC, fumiama commented on plugin/robbery/robbery.go
> +					ctx.SendChain(message.Text("打劫失败,您身上没有钱支付罚款"))
可以直接减为0.

2024-05-28 16:12 UTC, fumiama approved these changes

2024-05-28 16:12 UTC, merged