修改牛牛大作战的部分问题，添加新玩法赎牛牛
FloatTech/ZeroBot-Plugin pull request #970
Opened 2024-08-31 07:55 UTC by xyy0411

2024-08-31 15:09 UTC, fumiama requested changes

2024-08-31 15:09 UTC, fumiama commented on plugin/niuniu/main.go
> +	jjCount       = make(map[string]lastLength)
用`syncx.Map`

2024-08-31 15:09 UTC, fumiama commented on plugin/niuniu/main.go
> +		if time.Now().Sub(last.TimeLimit) > time.Minute*30 {
修lint

2024-08-31 15:09 UTC, fumiama commented on plugin/niuniu/main.go
> +		//获取初始长度
遵守代码格式化，别做无谓的更改。

2024-09-02 14:24 UTC, fumiama requested changes

2024-09-02 14:24 UTC, fumiama commented on plugin/niuniu/main.go
> +	jjCount       = sync.Map{}
syncx.Map，懂？
```go
syncx.Map[string, *lastLength]
```

2024-09-02 14:48 UTC, xyy0411 commented on plugin/niuniu/main.go
> +	jjCount       = sync.Map{}
我还以为你打错了

2024-09-03 12:36 UTC, fumiama requested changes

2024-09-03 12:36 UTC, fumiama commented on plugin/niuniu/main.go
> +				fmt.Sprintf("你们不要再找ta🤺啦！")})))
修lint，之后不要我提醒了，看到没全绿就去files changed看详情。

2024-09-03 15:21 UTC, fumiama approved these changes

2024-09-03 15:22 UTC, merged