修复niuniu的已知问题，添加新玩法牛牛商店
FloatTech/ZeroBot-Plugin pull request #974
Opened 2024-09-08 06:19 UTC by xyy0411

2024-09-10 16:22 UTC, fumiama requested changes
现在main里面业务逻辑还是太多太乱了，那些判断数值返回文本的东西，全部封装成函数放utils.go。

2024-09-10 16:22 UTC, fumiama commented on plugin/niuniu/main.go
> +/*func 渡劫成功与否(u userInfo, product bool) {
不要提交未经测试的代码，要不就全部做完再提交。

2024-09-10 16:22 UTC, fumiama commented on plugin/niuniu/main.go
> +		timer := time.NewTimer(120 * time.Second)
```go
defer timer.Stop()
```

2024-09-10 16:22 UTC, fumiama commented on plugin/niuniu/main.go
> +			ctx.SendChain(message.Text("赎牛牛需要150ATRI币，快去赚钱吧"))
明明150上面判断不改吗

2024-09-10 16:22 UTC, fumiama commented on plugin/niuniu/main.go
> +		} else {
不要if-else-switch，全部用switch就行了。

2024-09-10 16:22 UTC, fumiama commented on plugin/niuniu/main.go
> +		if ok && v.Count > 1 && time.Since(v.TimeLimit) < time.Minute*8 {
一个问题。

2024-09-14 07:36 UTC, fumiama requested changes

2024-09-14 07:36 UTC, fumiama commented on plugin/niuniu/utils.go
> +		ctx.SendChain(message.Text("你使用道具次数太快了，此次道具不会生效，等待", time.Minute*8-time.Since(v.TimeLimit), "再来吧"))
工具函数中不要出现ctx，报错也是一种消息，直接返回string即可。

2024-09-14 07:36 UTC, fumiama commented on plugin/niuniu/utils.go
> +		ctx.SendChain(message.Text("你使用道具次数太快了，此次道具不会生效，等待", time.Minute*8-time.Since(load.TimeLimit), "再来吧"))
同

2024-09-14 14:32 UTC, xyy0411 commented on plugin/niuniu/utils.go
> +		ctx.SendChain(message.Text("你使用道具次数太快了，此次道具不会生效，等待", time.Minute*8-time.Since(v.TimeLimit), "再来吧"))
返回error和string都一样吧，反正拿到后都得先判断是否非空

2024-09-15 15:37 UTC, fumiama requested changes

2024-09-15 15:37 UTC, fumiama commented on plugin/niuniu/main.go
> +		ctx.SendChain(message.Text(fmt.Sprintln("当前牛牛背包如下"),
其实你可以直接
```go
message.Text(
    "当前牛牛背包如下\n",
    "伟哥: ", niu.WeiGe,
    "媚药: ", niu.Philter,
    ...
)
```
其他**所有**类似的都这样修改。

2024-09-15 15:37 UTC, fumiama commented on plugin/niuniu/model.go
> +type NiuPlugin interface {
你完全没有明白我的意思，我的建议是先不要加了，先把现有功能改好合并之后你慢慢弄。

2024-09-26 07:28 UTC, fumiama approved these changes

2024-09-26 07:30 UTC, merged